import json

with open('data/exercises.json', 'r', encoding='utf-8') as f:
    data = json.load(f)

new_ko_ro = [
    {"lessonId":"T5-01","topik":5,"q":"알람이 안 울리는 바람에 늦잠을 잤어요.","answers":{"ro":["Din cauză că alarma nu a sunat, am dormit prea mult.","Am dormit prea mult pentru că am vrut.","Alarma a sunat și m-am trezit.","Am setat alarma dar am uitat-o."],"en":["Because the alarm didn't go off, I overslept.","I overslept because I wanted to.","The alarm went off and I woke up.","I set the alarm but forgot it."]},"correct":{"ro":"Din cauză că alarma nu a sunat, am dormit prea mult.","en":"Because the alarm didn't go off, I overslept."}},
    {"lessonId":"T5-01","topik":5,"q":"전화기가 고장 나는 바람에 연락을 못 했어요.","answers":{"ro":["Din cauză că telefonul s-a stricat, nu am putut lua legătura.","Am sunat dar nu mi-a răspuns.","Telefonul meu funcționează bine.","Nu am vrut să iau legătura."],"en":["Because my phone broke down, I couldn't contact anyone.","I called but no one answered.","My phone is working fine.","I didn't want to contact anyone."]},"correct":{"ro":"Din cauză că telefonul s-a stricat, nu am putut lua legătura.","en":"Because my phone broke down, I couldn't contact anyone."}},
    {"lessonId":"T5-02","topik":5,"q":"이 식당은 맛있을 뿐만 아니라 가격도 저렴해요.","answers":{"ro":["Acest restaurant nu este doar delicios, ci și prețul este accesibil.","Restaurantul este delicios dar scump.","Restaurantul are prețuri accesibile dar mâncarea nu e bună.","Nu îmi place nici mâncarea nici prețul."],"en":["This restaurant is not only delicious, but the price is also cheap.","The restaurant is delicious but expensive.","The restaurant has cheap prices but the food isn't good.","I don't like either the food or the price."]},"correct":{"ro":"Acest restaurant nu este doar delicios, ci și prețul este accesibil.","en":"This restaurant is not only delicious, but the price is also cheap."}},
    {"lessonId":"T5-02","topik":5,"q":"운동은 건강에 좋을 뿐만 아니라 스트레스 해소에도 도움이 돼요.","answers":{"ro":["Sportul nu este doar bun pentru sănătate, ci ajută și la eliminarea stresului.","Sportul e bun pentru sănătate dar obositor.","Nu fac sport pentru că e greu.","Sportul cauzează stres."],"en":["Exercise is not only good for health, but also helps with stress relief.","Exercise is good for health but tiring.","I don't exercise because it's hard.","Exercise causes stress."]},"correct":{"ro":"Sportul nu este doar bun pentru sănătate, ci ajută și la eliminarea stresului.","en":"Exercise is not only good for health, but also helps with stress relief."}},
    {"lessonId":"T5-03","topik":5,"q":"이 법은 정부에 의해 만들어졌어요.","answers":{"ro":["Această lege a fost creată de guvern.","Guvernul a anulat această lege.","Această lege nu există.","Cetățenii au creat această lege."],"en":["This law was made by the government.","The government abolished this law.","This law doesn't exist.","Citizens made this law."]},"correct":{"ro":"Această lege a fost creată de guvern.","en":"This law was made by the government."}},
    {"lessonId":"T5-03","topik":5,"q":"새로운 치료법이 과학자들에 의해 개발됐어요.","answers":{"ro":["Un nou tratament a fost dezvoltat de oameni de știință.","Oamenii de știință au respins tratamentul.","Tratamentul a fost inventat de pacienți.","Nu există tratamente noi."],"en":["A new treatment was developed by scientists.","Scientists rejected the treatment.","The treatment was invented by patients.","There are no new treatments."]},"correct":{"ro":"Un nou tratament a fost dezvoltat de oameni de știință.","en":"A new treatment was developed by scientists."}},
    {"lessonId":"T5-04","topik":5,"q":"학생 때 자주 읽던 책이에요.","answers":{"ro":["Aceasta este o carte pe care o citeam des pe când eram student/studentă.","Tocmai am cumpărat această carte.","Nu am citit niciodată această carte.","Această carte este nouă."],"en":["This is a book I often read when I was a student.","I just bought this book.","I've never read this book.","This book is new."]},"correct":{"ro":"Aceasta este o carte pe care o citeam des pe când eram student/studentă.","en":"This is a book I often read when I was a student."}},
    {"lessonId":"T5-04","topik":5,"q":"같이 놀던 친구를 오랜만에 만났어요.","answers":{"ro":["L-am întâlnit după mult timp pe prietenul cu care mă jucam împreună.","Mi-am întâlnit un prieten nou.","Nu mi-am văzut prietenul de mult.","Voi merge să-mi văd prietenul mâine."],"en":["I met a friend I used to play with after a long time.","I met a new friend.","I haven't seen my friend in a long time.","I'll go see my friend tomorrow."]},"correct":{"ro":"L-am întâlnit după mult timp pe prietenul cu care mă jucam împreună.","en":"I met a friend I used to play with after a long time."}},
    {"lessonId":"T5-05","topik":5,"q":"환경을 보호하고자 캠페인을 시작했어요.","answers":{"ro":["Am început o campanie cu intenția de a proteja mediul înconjurător.","Am participat la o campanie de mediu.","Nu sunt interesat/interesată de mediu.","Mediul înconjurător nu are nevoie de protecție."],"en":["We started a campaign with the intention of protecting the environment.","We participated in an environmental campaign.","I'm not interested in the environment.","The environment doesn't need protection."]},"correct":{"ro":"Am început o campanie cu intenția de a proteja mediul înconjurător.","en":"We started a campaign with the intention of protecting the environment."}},
    {"lessonId":"T5-05","topik":5,"q":"실력을 향상시키고자 매일 연습합니다.","answers":{"ro":["Exersez în fiecare zi cu intenția de a-mi îmbunătăți abilitățile.","Exersez uneori când am timp.","Nu exersez deloc.","Exersez pentru distracție."],"en":["I practice every day with the intention of improving my skills.","I practice sometimes when I have time.","I don't practice at all.","I practice for fun."]},"correct":{"ro":"Exersez în fiecare zi cu intenția de a-mi îmbunătăți abilitățile.","en":"I practice every day with the intention of improving my skills."}},
    {"lessonId":"T5-06","topik":5,"q":"그렇게 똑똑한 사람이 모를 리가 없어요.","answers":{"ro":["Nu este posibil ca o persoană atât de inteligentă să nu știe.","Acea persoană inteligentă nu știe.","Persoana nu este foarte inteligentă.","Este posibil ca persoana să nu știe."],"en":["There's no way that such a smart person doesn't know.","That smart person doesn't know.","The person is not very smart.","It's possible that the person doesn't know."]},"correct":{"ro":"Nu este posibil ca o persoană atât de inteligentă să nu știe.","en":"There's no way that such a smart person doesn't know."}},
    {"lessonId":"T5-06","topik":5,"q":"방금 밥을 먹었는데 배가 고플 리가 없어요.","answers":{"ro":["Tocmai am mâncat, deci nu este posibil să îmi fie foame.","Mi-e foame deși am mâncat.","Nu am mâncat nimic azi.","Este posibil să îmi fie foame."],"en":["I just ate, so there's no way I'm hungry.","I'm hungry even though I ate.","I haven't eaten anything today.","It's possible that I'm hungry."]},"correct":{"ro":"Tocmai am mâncat, deci nu este posibil să îmi fie foame.","en":"I just ate, so there's no way I'm hungry."}},
    {"lessonId":"T5-07","topik":5,"q":"느끼다시피 오늘 분위기가 좋지 않아요.","answers":{"ro":["Cum puteți simți, atmosfera de azi nu este bună.","Atmosfera de azi este foarte bună.","Nu simt nimic special azi.","Atmosfera a fost mai rea ieri."],"en":["As you can feel, the atmosphere today is not good.","The atmosphere today is very good.","I don't feel anything special today.","The atmosphere was worse yesterday."]},"correct":{"ro":"Cum puteți simți, atmosfera de azi nu este bună.","en":"As you can feel, the atmosphere today is not good."}},
    {"lessonId":"T5-07","topik":5,"q":"예상하다시피 결과가 좋지 않았어요.","answers":{"ro":["Cum era de așteptat, rezultatele nu au fost bune.","Rezultatele au fost surprinzător de bune.","Nimeni nu s-a așteptat la aceste rezultate.","Rezultatele nu au fost anunțate."],"en":["As expected, the results were not good.","The results were surprisingly good.","No one expected these results.","The results haven't been announced."]},"correct":{"ro":"Cum era de așteptat, rezultatele nu au fost bune.","en":"As expected, the results were not good."}},
    {"lessonId":"T5-08","topik":5,"q":"그 말을 듣지 않았더라면 실수를 안 했을 거예요.","answers":{"ro":["Dacă nu aș fi ascultat acele cuvinte, nu aș fi făcut greșeala.","Am ascultat sfatul și a mers bine.","Am făcut greșeala intenționat.","Nu am ascultat niciun sfat."],"en":["If I hadn't listened to those words, I wouldn't have made a mistake.","I listened to the advice and it went well.","I made the mistake on purpose.","I didn't listen to any advice."]},"correct":{"ro":"Dacă nu aș fi ascultat acele cuvinte, nu aș fi făcut greșeala.","en":"If I hadn't listened to those words, I wouldn't have made a mistake."}},
    {"lessonId":"T5-08","topik":5,"q":"우산을 가져왔더라면 좋았을 텐데.","answers":{"ro":["Ar fi fost bine dacă aș fi adus umbrela.","Am adus umbrela și m-a ajutat.","Nu am nevoie de umbrelă.","Am uitat umbrela acasă în mod intenționat."],"en":["It would have been good if I had brought an umbrella.","I brought the umbrella and it helped.","I don't need an umbrella.","I intentionally left the umbrella at home."]},"correct":{"ro":"Ar fi fost bine dacă aș fi adus umbrela.","en":"It would have been good if I had brought an umbrella."}},
    {"lessonId":"T5-09","topik":5,"q":"이 책은 읽을 만해요.","answers":{"ro":["Această carte merită citită.","Această carte nu merită citită.","Cartea este prea grea.","Nu am citit această carte."],"en":["This book is worth reading.","This book is not worth reading.","The book is too difficult.","I haven't read this book."]},"correct":{"ro":"Această carte merită citită.","en":"This book is worth reading."}},
    {"lessonId":"T5-09","topik":5,"q":"한번 가 볼 만한 곳이에요.","answers":{"ro":["Este un loc care merită vizitat cel puțin o dată.","Nu merită să vizitezi acest loc.","Locul este prea departe.","Nu știu unde se află acest loc."],"en":["It's a place worth visiting.","This place is not worth visiting.","The place is too far.","I don't know where this place is."]},"correct":{"ro":"Este un loc care merită vizitat cel puțin o dată.","en":"It's a place worth visiting."}},
    {"lessonId":"T5-10","topik":5,"q":"자는 척하면서 이야기를 들었어요.","answers":{"ro":["M-am prefăcut că dorm și am ascultat conversația.","Am adormit și nu am auzit nimic.","Am ascultat conversația deschis.","Nu am auzit nicio conversație."],"en":["I pretended to sleep and listened to the conversation.","I fell asleep and didn't hear anything.","I listened to the conversation openly.","I didn't hear any conversation."]},"correct":{"ro":"M-am prefăcut că dorm și am ascultat conversația.","en":"I pretended to sleep and listened to the conversation."}},
    {"lessonId":"T5-10","topik":5,"q":"바쁜 척해서 전화를 안 받았어요.","answers":{"ro":["M-am prefăcut că sunt ocupat/ocupată și nu am răspuns la telefon.","Eram cu adevărat ocupat/ocupată și nu am putut răspunde.","Am răspuns la telefon imediat.","Nu am auzit telefonul."],"en":["I pretended to be busy and didn't answer the phone.","I was really busy and couldn't answer.","I answered the phone immediately.","I didn't hear the phone."]},"correct":{"ro":"M-am prefăcut că sunt ocupat/ocupată și nu am răspuns la telefon.","en":"I pretended to be busy and didn't answer the phone."}},
    {"lessonId":"T5-11","topik":5,"q":"배가 고플 텐데 같이 밥 먹어요.","answers":{"ro":["Probabil că ți-e foame, să mâncăm împreună.","Să mâncăm împreună mâine.","Nu mi-e foame deloc.","Am mâncat deja."],"en":["You must be hungry, let's eat together.","Let's eat together tomorrow.","I'm not hungry at all.","I've already eaten."]},"correct":{"ro":"Probabil că ți-e foame, să mâncăm împreună.","en":"You must be hungry, let's eat together."}},
    {"lessonId":"T5-11","topik":5,"q":"어렵겠지만 할 수 있을 텐데요.","answers":{"ro":["Poate fi greu, dar ar trebui să poți reuși.","Este prea greu, nu poți reuși.","Este foarte ușor.","Nu trebuie să încerci."],"en":["It might be difficult, but you should be able to do it.","It's too difficult, you can't do it.","It's very easy.","You don't need to try."]},"correct":{"ro":"Poate fi greu, dar ar trebui să poți reuși.","en":"It might be difficult, but you should be able to do it."}},
]

new_ro_ko = [
    {"lessonId":"T5-01","topik":5,"prompt":{"ro":"Din cauză că alarma nu a sunat, am dormit prea mult.","en":"Because the alarm didn't go off, I overslept."},"options":["알람이 안 울리는 바람에 늦잠을 잤어요.","알람이 울려서 일찍 일어났어요.","늦잠을 자고 싶어서 알람을 껐어요.","알람을 맞추지 않았어요."],"correct":"알람이 안 울리는 바람에 늦잠을 잤어요."},
    {"lessonId":"T5-01","topik":5,"prompt":{"ro":"Din cauză că telefonul s-a stricat, nu am putut lua legătura.","en":"Because my phone broke down, I couldn't contact anyone."},"options":["전화기가 고장 나는 바람에 연락을 못 했어요.","전화기가 고장 나서 새로 샀어요.","전화기로 연락을 했어요.","연락하고 싶지 않았어요."],"correct":"전화기가 고장 나는 바람에 연락을 못 했어요."},
    {"lessonId":"T5-02","topik":5,"prompt":{"ro":"Acest restaurant nu este doar delicios, ci și prețul este accesibil.","en":"This restaurant is not only delicious, but the price is also cheap."},"options":["이 식당은 맛있을 뿐만 아니라 가격도 저렴해요.","이 식당은 맛있지만 비싸요.","이 식당의 가격이 싸지 않아요.","이 식당은 맛있어요."],"correct":"이 식당은 맛있을 뿐만 아니라 가격도 저렴해요."},
    {"lessonId":"T5-02","topik":5,"prompt":{"ro":"Sportul nu este doar bun pentru sănătate, ci ajută și la eliminarea stresului.","en":"Exercise is not only good for health, but also helps with stress relief."},"options":["운동은 건강에 좋을 뿐만 아니라 스트레스 해소에도 도움이 돼요.","운동은 건강에 좋지만 스트레스를 줘요.","운동은 건강에 좋아요.","운동은 스트레스에 도움이 되지 않아요."],"correct":"운동은 건강에 좋을 뿐만 아니라 스트레스 해소에도 도움이 돼요."},
    {"lessonId":"T5-03","topik":5,"prompt":{"ro":"Această lege a fost creată de guvern.","en":"This law was made by the government."},"options":["이 법은 정부에 의해 만들어졌어요.","정부가 이 법을 없앴어요.","시민들이 이 법을 만들었어요.","이 법은 오래됐어요."],"correct":"이 법은 정부에 의해 만들어졌어요."},
    {"lessonId":"T5-03","topik":5,"prompt":{"ro":"Un nou tratament a fost dezvoltat de oameni de știință.","en":"A new treatment was developed by scientists."},"options":["새로운 치료법이 과학자들에 의해 개발됐어요.","과학자들이 치료법을 거부했어요.","환자들이 치료법을 개발했어요.","새로운 치료법이 없어요."],"correct":"새로운 치료법이 과학자들에 의해 개발됐어요."},
    {"lessonId":"T5-04","topik":5,"prompt":{"ro":"Aceasta este o carte pe care o citeam des pe când eram student/studentă.","en":"This is a book I often read when I was a student."},"options":["학생 때 자주 읽던 책이에요.","방금 산 책이에요.","한 번도 읽지 않은 책이에요.","새로운 책이에요."],"correct":"학생 때 자주 읽던 책이에요."},
    {"lessonId":"T5-04","topik":5,"prompt":{"ro":"L-am întâlnit după mult timp pe prietenul cu care mă jucam împreună.","en":"I met a friend I used to play with after a long time."},"options":["같이 놀던 친구를 오랜만에 만났어요.","새로운 친구를 만났어요.","오랫동안 친구를 못 만났어요.","내일 친구를 만날 거예요."],"correct":"같이 놀던 친구를 오랜만에 만났어요."},
    {"lessonId":"T5-05","topik":5,"prompt":{"ro":"Am început o campanie cu intenția de a proteja mediul înconjurător.","en":"We started a campaign with the intention of protecting the environment."},"options":["환경을 보호하고자 캠페인을 시작했어요.","캠페인에 참여했어요.","환경에 관심이 없어요.","캠페인이 끝났어요."],"correct":"환경을 보호하고자 캠페인을 시작했어요."},
    {"lessonId":"T5-05","topik":5,"prompt":{"ro":"Exersez în fiecare zi cu intenția de a-mi îmbunătăți abilitățile.","en":"I practice every day with the intention of improving my skills."},"options":["실력을 향상시키고자 매일 연습합니다.","가끔 연습해요.","연습을 안 해요.","재미로 연습해요."],"correct":"실력을 향상시키고자 매일 연습합니다."},
    {"lessonId":"T5-06","topik":5,"prompt":{"ro":"Nu este posibil ca o persoană atât de inteligentă să nu știe.","en":"There's no way that such a smart person doesn't know."},"options":["그렇게 똑똑한 사람이 모를 리가 없어요.","그 똑똑한 사람이 모르고 있어요.","그 사람은 똑똑하지 않아요.","그 사람이 알지 모르는지 몰라요."],"correct":"그렇게 똑똑한 사람이 모를 리가 없어요."},
    {"lessonId":"T5-06","topik":5,"prompt":{"ro":"Tocmai am mâncat, deci nu este posibil să îmi fie foame.","en":"I just ate, so there's no way I'm hungry."},"options":["방금 밥을 먹었는데 배가 고플 리가 없어요.","밥을 먹었는데 배가 고파요.","밥을 안 먹어서 배가 고파요.","배가 고플 수도 있어요."],"correct":"방금 밥을 먹었는데 배가 고플 리가 없어요."},
    {"lessonId":"T5-07","topik":5,"prompt":{"ro":"Cum puteți simți, atmosfera de azi nu este bună.","en":"As you can feel, the atmosphere today is not good."},"options":["느끼다시피 오늘 분위기가 좋지 않아요.","오늘 분위기가 아주 좋아요.","오늘 아무것도 못 느껴요.","어제보다 분위기가 나빠요."],"correct":"느끼다시피 오늘 분위기가 좋지 않아요."},
    {"lessonId":"T5-07","topik":5,"prompt":{"ro":"Cum era de așteptat, rezultatele nu au fost bune.","en":"As expected, the results were not good."},"options":["예상하다시피 결과가 좋지 않았어요.","결과가 놀랍게 좋았어요.","아무도 이 결과를 예상 못 했어요.","결과가 아직 발표 안 됐어요."],"correct":"예상하다시피 결과가 좋지 않았어요."},
    {"lessonId":"T5-08","topik":5,"prompt":{"ro":"Dacă nu aș fi ascultat acele cuvinte, nu aș fi făcut greșeala.","en":"If I hadn't listened to those words, I wouldn't have made a mistake."},"options":["그 말을 듣지 않았더라면 실수를 안 했을 거예요.","그 말을 들어서 잘 됐어요.","일부러 실수를 했어요.","아무 말도 듣지 않았어요."],"correct":"그 말을 듣지 않았더라면 실수를 안 했을 거예요."},
    {"lessonId":"T5-08","topik":5,"prompt":{"ro":"Ar fi fost bine dacă aș fi adus umbrela.","en":"It would have been good if I had brought an umbrella."},"options":["우산을 가져왔더라면 좋았을 텐데.","우산을 가져와서 다행이었어요.","우산이 필요 없었어요.","일부러 우산을 두고 왔어요."],"correct":"우산을 가져왔더라면 좋았을 텐데."},
    {"lessonId":"T5-09","topik":5,"prompt":{"ro":"Această carte merită citită.","en":"This book is worth reading."},"options":["이 책은 읽을 만해요.","이 책은 읽을 가치가 없어요.","이 책은 너무 어려워요.","이 책을 읽지 않았어요."],"correct":"이 책은 읽을 만해요."},
    {"lessonId":"T5-09","topik":5,"prompt":{"ro":"Este un loc care merită vizitat cel puțin o dată.","en":"It's a place worth visiting."},"options":["한번 가 볼 만한 곳이에요.","가지 않아도 되는 곳이에요.","그 곳은 너무 멀어요.","그 곳이 어딘지 몰라요."],"correct":"한번 가 볼 만한 곳이에요."},
    {"lessonId":"T5-10","topik":5,"prompt":{"ro":"M-am prefăcut că dorm și am ascultat conversația.","en":"I pretended to sleep and listened to the conversation."},"options":["자는 척하면서 이야기를 들었어요.","잠이 들어서 아무것도 못 들었어요.","솔직하게 이야기를 들었어요.","이야기를 전혀 못 들었어요."],"correct":"자는 척하면서 이야기를 들었어요."},
    {"lessonId":"T5-10","topik":5,"prompt":{"ro":"M-am prefăcut că sunt ocupat/ocupată și nu am răspuns la telefon.","en":"I pretended to be busy and didn't answer the phone."},"options":["바쁜 척해서 전화를 안 받았어요.","정말 바빠서 전화를 못 받았어요.","전화를 바로 받았어요.","전화 소리를 못 들었어요."],"correct":"바쁜 척해서 전화를 안 받았어요."},
    {"lessonId":"T5-11","topik":5,"prompt":{"ro":"Probabil că ți-e foame, să mâncăm împreună.","en":"You must be hungry, let's eat together."},"options":["배가 고플 텐데 같이 밥 먹어요.","내일 같이 밥 먹어요.","배가 안 고파요.","이미 밥을 먹었어요."],"correct":"배가 고플 텐데 같이 밥 먹어요."},
    {"lessonId":"T5-11","topik":5,"prompt":{"ro":"Poate fi greu, dar ar trebui să poți reuși.","en":"It might be difficult, but you should be able to do it."},"options":["어렵겠지만 할 수 있을 텐데요.","너무 어려워서 못 할 거예요.","아주 쉬운 일이에요.","하려고 노력하지 않아도 돼요."],"correct":"어렵겠지만 할 수 있을 텐데요."},
]

new_particle = [
    {"lessonId":"T5-01","topik":5,"template":"알람___ 안 울리는 바람에 늦잠을 잤어요.","options":["이","가","을","도"],"correct":"이","hint":{"ro":"Subiect: 알람 — se termină în consoană → 이","en":"Subject: 알람 — ends in consonant → 이"}},
    {"lessonId":"T5-01","topik":5,"template":"전화기___ 고장 나는 바람에 연락을 못 했어요.","options":["가","이","를","는"],"correct":"가","hint":{"ro":"Subiect: 전화기 — se termină în vocală → 가","en":"Subject: 전화기 — ends in vowel → 가"}},
    {"lessonId":"T5-02","topik":5,"template":"이 식당___ 맛있을 뿐만 아니라 가격도 저렴해요.","options":["은","이","를","에"],"correct":"은","hint":{"ro":"Topic: 식당 — se termină în consoană → 은","en":"Topic: 식당 — ends in consonant → 은"}},
    {"lessonId":"T5-02","topik":5,"template":"운동은 건강___ 좋을 뿐만 아니라 스트레스 해소에도 도움이 돼요.","options":["에","를","이","도"],"correct":"에","hint":{"ro":"건강에 좋다 = bun pentru sănătate (particulă fixă 에)","en":"건강에 좋다 = good for health (fixed particle 에)"}},
    {"lessonId":"T5-03","topik":5,"template":"이 법은 정부___ 의해 만들어졌어요.","options":["에","를","이","도"],"correct":"에","hint":{"ro":"에 의해 = de către (particulă fixă 에)","en":"에 의해 = by (fixed particle 에)"}},
    {"lessonId":"T5-03","topik":5,"template":"새로운 치료법___ 과학자들에 의해 개발됐어요.","options":["이","가","을","는"],"correct":"이","hint":{"ro":"Subiect: 치료법 — se termină în consoană → 이","en":"Subject: 치료법 — ends in consonant → 이"}},
    {"lessonId":"T5-04","topik":5,"template":"학생 때 자주 읽던 책___ 빌렸어요.","options":["을","이","는","에"],"correct":"을","hint":{"ro":"Complement direct: 책 — se termină în consoană → 을","en":"Object: 책 — ends in consonant → 을"}},
    {"lessonId":"T5-04","topik":5,"template":"같이 놀던 친구___ 오랜만에 만났어요.","options":["를","이","는","에"],"correct":"를","hint":{"ro":"Complement direct: 친구 — se termină în vocală → 를","en":"Object: 친구 — ends in vowel → 를"}},
    {"lessonId":"T5-05","topik":5,"template":"환경___ 보호하고자 캠페인을 시작했어요.","options":["을","이","는","에"],"correct":"을","hint":{"ro":"Complement direct: 환경 — se termină în consoană → 을","en":"Object: 환경 — ends in consonant → 을"}},
    {"lessonId":"T5-05","topik":5,"template":"실력___ 향상시키고자 매일 연습합니다.","options":["을","이","는","에"],"correct":"을","hint":{"ro":"Complement direct: 실력 — se termină în consoană → 을","en":"Object: 실력 — ends in consonant → 을"}},
    {"lessonId":"T5-06","topik":5,"template":"그렇게 똑똑한 사람___ 모를 리가 없어요.","options":["이","가","을","도"],"correct":"이","hint":{"ro":"Subiect: 사람 — se termină în consoană → 이","en":"Subject: 사람 — ends in consonant → 이"}},
    {"lessonId":"T5-06","topik":5,"template":"방금 밥___ 먹었는데 배가 고플 리가 없어요.","options":["을","이","는","에"],"correct":"을","hint":{"ro":"Complement direct: 밥 — se termină în consoană → 을","en":"Object: 밥 — ends in consonant → 을"}},
    {"lessonId":"T5-07","topik":5,"template":"느끼다시피 오늘 분위기___ 좋지 않아요.","options":["가","는","이","를"],"correct":"가","hint":{"ro":"Subiect: 분위기 — se termină în vocală → 가","en":"Subject: 분위기 — ends in vowel → 가"}},
    {"lessonId":"T5-07","topik":5,"template":"예상하다시피 결과___ 좋지 않았어요.","options":["가","는","이","를"],"correct":"가","hint":{"ro":"Subiect: 결과 — se termină în vocală → 가","en":"Subject: 결과 — ends in vowel → 가"}},
    {"lessonId":"T5-08","topik":5,"template":"그 말___ 듣지 않았더라면 실수를 안 했을 거예요.","options":["을","이","는","에"],"correct":"을","hint":{"ro":"Complement direct: 말 — se termină în consoană → 을","en":"Object: 말 — ends in consonant → 을"}},
    {"lessonId":"T5-08","topik":5,"template":"우산___ 가져왔더라면 좋았을 텐데.","options":["을","이","는","에"],"correct":"을","hint":{"ro":"Complement direct: 우산 — se termină în consoană → 을","en":"Object: 우산 — ends in consonant → 을"}},
    {"lessonId":"T5-09","topik":5,"template":"이 책___ 읽을 만해요.","options":["은","이","를","에"],"correct":"은","hint":{"ro":"Topic: 책 — se termină în consoană → 은","en":"Topic: 책 — ends in consonant → 은"}},
    {"lessonId":"T5-09","topik":5,"template":"한번 가 볼 만한 곳___ 추천해요.","options":["을","이","는","에"],"correct":"을","hint":{"ro":"Complement direct: 곳 — se termină în consoană → 을","en":"Object: 곳 — ends in consonant → 을"}},
    {"lessonId":"T5-10","topik":5,"template":"자는 척하면서 이야기___ 들었어요.","options":["를","이","은","에"],"correct":"를","hint":{"ro":"Complement direct: 이야기 — se termină în vocală → 를","en":"Object: 이야기 — ends in vowel → 를"}},
    {"lessonId":"T5-10","topik":5,"template":"바쁜 척해서 전화___ 안 받았어요.","options":["를","이","은","에"],"correct":"를","hint":{"ro":"Complement direct: 전화 — se termină în vocală → 를","en":"Object: 전화 — ends in vowel → 를"}},
    {"lessonId":"T5-11","topik":5,"template":"배___ 고플 텐데 같이 밥 먹어요.","options":["가","는","이","를"],"correct":"가","hint":{"ro":"Subiect: 배 (burtă) — se termină în vocală → 가","en":"Subject: 배 (stomach) — ends in vowel → 가"}},
    {"lessonId":"T5-11","topik":5,"template":"숙제___ 어렵겠지만 할 수 있을 텐데요.","options":["가","를","은","이"],"correct":"가","hint":{"ro":"Subiect: 숙제 — se termină în vocală → 가","en":"Subject: 숙제 — ends in vowel → 가"}},
]

new_particle_plus = [
    {"lessonId":"T5-01","topik":5,"template":"알람___ 안 울리는 바람에 늦잠___ 잤어요.","options":[["이","을"],["가","을"],["이","를"],["가","를"]],"correct":["이","을"],"hint":{"ro":"알람 (consoană→이, subiect), 늦잠 (consoană→을, obiect)","en":"알람 (consonant→이, subject), 늦잠 (consonant→을, object)"}},
    {"lessonId":"T5-01","topik":5,"template":"전화기___ 고장 나는 바람에 연락___ 못 했어요.","options":[["가","을"],["이","을"],["가","를"],["이","를"]],"correct":["가","을"],"hint":{"ro":"전화기 (vocală→가, subiect), 연락 (consoană→을, obiect)","en":"전화기 (vowel→가, subject), 연락 (consonant→을, object)"}},
    {"lessonId":"T5-02","topik":5,"template":"이 식당___ 맛있을 뿐만 아니라 가격___ 저렴해요.","options":[["은","도"],["이","도"],["은","가"],["는","도"]],"correct":["은","도"],"hint":{"ro":"식당 (consoană→은, topic), 가격도 = și prețul (도)","en":"식당 (consonant→은, topic), 가격도 = also the price (도)"}},
    {"lessonId":"T5-02","topik":5,"template":"운동___ 건강에 좋을 뿐만 아니라 스트레스 해소___ 도움이 돼요.","options":[["은","에"],["이","에"],["는","에"],["은","를"]],"correct":["은","에"],"hint":{"ro":"운동 (consoană→은, topic), 스트레스 해소에 = pentru eliminarea stresului (에)","en":"운동 (consonant→은, topic), 스트레스 해소에 = for stress relief (에)"}},
    {"lessonId":"T5-03","topik":5,"template":"이 법___ 정부___ 의해 만들어졌어요.","options":[["은","에"],["이","에"],["는","에"],["을","에"]],"correct":["은","에"],"hint":{"ro":"법 (consoană→은, topic), 정부에 의해 = de guvern (에 fix)","en":"법 (consonant→은, topic), 정부에 의해 = by the government (fixed 에)"}},
    {"lessonId":"T5-03","topik":5,"template":"새로운 치료법___ 과학자들___ 의해 개발됐어요.","options":[["이","에"],["가","에"],["이","를"],["가","에"]],"correct":["이","에"],"hint":{"ro":"치료법 (consoană→이, subiect), 과학자들에 의해 = de oamenii de știință (에 fix)","en":"치료법 (consonant→이, subject), 과학자들에 의해 = by scientists (fixed 에)"}},
    {"lessonId":"T5-04","topik":5,"template":"학생 때 읽던 책___ 재미있고 작가___ 유명해요.","options":[["도","가"],["이","가"],["도","이"],["을","가"]],"correct":["도","가"],"hint":{"ro":"책도 = și cartea (도), 작가 (vocală→가, subiect)","en":"책도 = also the book (도), 작가 (vowel→가, subject)"}},
    {"lessonId":"T5-04","topik":5,"template":"같이 놀던 친구___ 오랜만에 만났고 밥___ 같이 먹었어요.","options":[["를","을"],["이","을"],["를","이"],["가","을"]],"correct":["를","을"],"hint":{"ro":"친구 (vocală→를, obiect), 밥 (consoană→을, obiect)","en":"친구 (vowel→를, object), 밥 (consonant→을, object)"}},
    {"lessonId":"T5-05","topik":5,"template":"환경___ 보호하고자 캠페인___ 시작했어요.","options":[["을","을"],["이","을"],["을","를"],["를","을"]],"correct":["을","을"],"hint":{"ro":"환경 (consoană→을, obiect), 캠페인 (consoană→을, obiect)","en":"환경 (consonant→을, object), 캠페인 (consonant→을, object)"}},
    {"lessonId":"T5-05","topik":5,"template":"우리___ 실력___ 향상시키고자 매일 연습합니다.","options":[["는","을"],["이","을"],["는","를"],["가","을"]],"correct":["는","을"],"hint":{"ro":"우리 (vocală→는, topic), 실력 (consoană→을, obiect)","en":"우리 (vowel→는, topic), 실력 (consonant→을, object)"}},
    {"lessonId":"T5-06","topik":5,"template":"그렇게 똑똑한 사람___ 이 문제___ 모를 리가 없어요.","options":[["이","를"],["가","를"],["이","을"],["가","이"]],"correct":["이","를"],"hint":{"ro":"사람 (consoană→이, subiect), 문제 (vocală→를, obiect)","en":"사람 (consonant→이, subject), 문제 (vowel→를, object)"}},
    {"lessonId":"T5-06","topik":5,"template":"방금 밥___ 먹었는데 배___ 고플 리가 없어요.","options":[["을","가"],["이","가"],["를","가"],["을","이"]],"correct":["을","가"],"hint":{"ro":"밥 (consoană→을, obiect), 배 (vocală→가, subiect)","en":"밥 (consonant→을, object), 배 (vowel→가, subject)"}},
    {"lessonId":"T5-07","topik":5,"template":"느끼다시피 오늘 분위기___ 좋지 않고 결과___ 좋지 않아요.","options":[["가","도"],["이","도"],["가","는"],["이","가"]],"correct":["가","도"],"hint":{"ro":"분위기 (vocală→가, subiect), 결과도 = și rezultatul (도)","en":"분위기 (vowel→가, subject), 결과도 = also the result (도)"}},
    {"lessonId":"T5-07","topik":5,"template":"예상하다시피 결과___ 좋지 않아서 팀___ 실망했어요.","options":[["가","이"],["이","이"],["가","가"],["는","이"]],"correct":["가","이"],"hint":{"ro":"결과 (vocală→가, subiect), 팀 (consoană→이, subiect)","en":"결과 (vowel→가, subject), 팀 (consonant→이, subject)"}},
    {"lessonId":"T5-08","topik":5,"template":"그 말___ 듣지 않았더라면 실수___ 안 했을 거예요.","options":[["을","를"],["이","를"],["을","이"],["가","를"]],"correct":["을","를"],"hint":{"ro":"말 (consoană→을, obiect), 실수 (vocală→를, obiect)","en":"말 (consonant→을, object), 실수 (vowel→를, object)"}},
    {"lessonId":"T5-08","topik":5,"template":"우산___ 가져왔더라면 비___ 안 맞았을 텐데요.","options":[["을","를"],["이","를"],["을","이"],["가","를"]],"correct":["을","를"],"hint":{"ro":"우산 (consoană→을, obiect), 비 (vocală→를, obiect)","en":"우산 (consonant→을, object), 비 (vowel→를, object)"}},
    {"lessonId":"T5-09","topik":5,"template":"이 책___ 읽어 보면 내용___ 재미있을 거예요.","options":[["을","이"],["이","이"],["를","이"],["을","가"]],"correct":["을","이"],"hint":{"ro":"책 (consoană→을, obiect), 내용 (consoană→이, subiect)","en":"책 (consonant→을, object), 내용 (consonant→이, subject)"}},
    {"lessonId":"T5-09","topik":5,"template":"한번 가 볼 만한 곳___ 친구___ 추천해 줬어요.","options":[["을","에게"],["이","에게"],["를","에게"],["을","에"]],"correct":["을","에게"],"hint":{"ro":"곳 (consoană→을, obiect), 친구에게 = prietenului (에게 = unei persoane)","en":"곳 (consonant→을, object), 친구에게 = to a friend (에게 = to a person)"}},
    {"lessonId":"T5-10","topik":5,"template":"자는 척하면서 이야기___ 들었고 아무것___ 모르는 척했어요.","options":[["를","도"],["을","도"],["이","도"],["를","는"]],"correct":["를","도"],"hint":{"ro":"이야기 (vocală→를, obiect), 아무것도 = nimic (도)","en":"이야기 (vowel→를, object), 아무것도 = nothing (도)"}},
    {"lessonId":"T5-10","topik":5,"template":"바쁜 척해서 전화___ 안 받았고 약속___ 취소했어요.","options":[["를","을"],["이","을"],["를","이"],["가","을"]],"correct":["를","을"],"hint":{"ro":"전화 (vocală→를, obiect), 약속 (consoană→을, obiect)","en":"전화 (vowel→를, object), 약속 (consonant→을, object)"}},
    {"lessonId":"T5-11","topik":5,"template":"배___ 고플 텐데 음식___ 같이 먹어요.","options":[["가","을"],["이","을"],["가","를"],["가","이"]],"correct":["가","을"],"hint":{"ro":"배 (vocală→가, subiect), 음식 (consoană→을, obiect)","en":"배 (vowel→가, subject), 음식 (consonant→을, object)"}},
    {"lessonId":"T5-11","topik":5,"template":"일___ 어렵겠지만 열심히 하면 결과___ 좋을 텐데요.","options":[["이","가"],["가","가"],["이","이"],["를","가"]],"correct":["이","가"],"hint":{"ro":"일 (consoană→이, subiect), 결과 (vocală→가, subiect)","en":"일 (consonant→이, subject), 결과 (vowel→가, subject)"}},
]

new_conjug = [
    {"lessonId":"T5-01","topik":5,"prompt":{"ro":"울리다 → din cauză că nu a sunat (-는 바람에)","en":"울리다 → because it didn't ring (-는 바람에)"},"options":["안 울리는 바람에","안 울린 바람에","안 울렸는 바람에","안 울릴 바람에"],"correct":"안 울리는 바람에"},
    {"lessonId":"T5-01","topik":5,"prompt":{"ro":"고장 나다 → din cauză că s-a stricat (-는 바람에)","en":"고장 나다 → because it broke down (-는 바람에)"},"options":["고장 나는 바람에","고장 난 바람에","고장 났는 바람에","고장 날 바람에"],"correct":"고장 나는 바람에"},
    {"lessonId":"T5-02","topik":5,"prompt":{"ro":"맛있다 → nu numai delicios (-(으)ㄹ 뿐만 아니라, adjectiv)","en":"맛있다 → not only delicious (-(으)ㄹ 뿐만 아니라, adjective)"},"options":["맛있을 뿐만 아니라","맛있는 뿐만 아니라","맛있은 뿐만 아니라","맛있어 뿐만 아니라"],"correct":"맛있을 뿐만 아니라"},
    {"lessonId":"T5-02","topik":5,"prompt":{"ro":"좋다 → nu numai bun (-(으)ㄹ 뿐만 아니라)","en":"좋다 → not only good (-(으)ㄹ 뿐만 아니라)"},"options":["좋을 뿐만 아니라","좋는 뿐만 아니라","좋은 뿐만 아니라","좋아 뿐만 아니라"],"correct":"좋을 뿐만 아니라"},
    {"lessonId":"T5-03","topik":5,"prompt":{"ro":"만들다 → a fost creat (pasiv cu -에 의해, trecut)","en":"만들다 → was made (passive with -에 의해, past)"},"options":["만들어졌어요","만들어요","만들었어요","만들어 있어요"],"correct":"만들어졌어요"},
    {"lessonId":"T5-03","topik":5,"prompt":{"ro":"개발하다 → a fost dezvoltat (pasiv cu -에 의해, trecut)","en":"개발하다 → was developed (passive with -에 의해, past)"},"options":["개발됐어요","개발했어요","개발되어요","개발시켰어요"],"correct":"개발됐어요"},
    {"lessonId":"T5-04","topik":5,"prompt":{"ro":"읽다 → citeam des (obișnuință trecută cu -던)","en":"읽다 → used to read often (past habitual -던)"},"options":["읽던","읽는","읽은","읽었던"],"correct":"읽던"},
    {"lessonId":"T5-04","topik":5,"prompt":{"ro":"놀다 → mă jucam împreună (obișnuință trecută cu -던, tulpină ㄹ)","en":"놀다 → used to play together (past habitual -던, ㄹ stem)"},"options":["놀던","노는","논","놀았던"],"correct":"놀던"},
    {"lessonId":"T5-05","topik":5,"prompt":{"ro":"보호하다 → cu intenția de a proteja (-고자)","en":"보호하다 → with the intention to protect (-고자)"},"options":["보호하고자","보호하려고","보호해서","보호하기 위해"],"correct":"보호하고자"},
    {"lessonId":"T5-05","topik":5,"prompt":{"ro":"향상시키다 → cu intenția de a îmbunătăți (-고자)","en":"향상시키다 → with the intention to improve (-고자)"},"options":["향상시키고자","향상시키려고","향상시켜서","향상시키기 위해"],"correct":"향상시키고자"},
    {"lessonId":"T5-06","topik":5,"prompt":{"ro":"모르다 → nu este posibil să nu știe (-(으)ㄹ 리가 없다, neregulat 르)","en":"모르다 → there's no way they don't know (-(으)ㄹ 리가 없다, 르 irregular)"},"options":["모를 리가 없어요","모르를 리가 없어요","모른 리가 없어요","모르는 리가 없어요"],"correct":"모를 리가 없어요"},
    {"lessonId":"T5-06","topik":5,"prompt":{"ro":"고프다 → nu este posibil să fie foame (-(으)ㄹ 리가 없다)","en":"고프다 → there's no way to be hungry (-(으)ㄹ 리가 없다)"},"options":["고플 리가 없어요","고프를 리가 없어요","고픈 리가 없어요","고파 리가 없어요"],"correct":"고플 리가 없어요"},
    {"lessonId":"T5-07","topik":5,"prompt":{"ro":"느끼다 → după cum poți simți (-다시피)","en":"느끼다 → as you can feel (-다시피)"},"options":["느끼다시피","느끼었다시피","느끼는다시피","느낀다시피"],"correct":"느끼다시피"},
    {"lessonId":"T5-07","topik":5,"prompt":{"ro":"예상하다 → după cum era de așteptat (-다시피)","en":"예상하다 → as expected (-다시피)"},"options":["예상하다시피","예상했다시피","예상하는다시피","예상한다시피"],"correct":"예상하다시피"},
    {"lessonId":"T5-08","topik":5,"prompt":{"ro":"듣다 → dacă nu ar fi ascultat (ㄷ-neregulat + -지 않았더라면)","en":"듣다 → if hadn't listened (ㄷ-irregular + -지 않았더라면)"},"options":["듣지 않았더라면","들지 않았더라면","듣지 않았드라면","들었지 않았더라면"],"correct":"듣지 않았더라면"},
    {"lessonId":"T5-08","topik":5,"prompt":{"ro":"가져오다 → dacă ar fi adus (-았/었더라면)","en":"가져오다 → if had brought (-았/었더라면)"},"options":["가져왔더라면","가져오았더라면","가져오었더라면","가져왔다라면"],"correct":"가져왔더라면"},
    {"lessonId":"T5-09","topik":5,"prompt":{"ro":"읽다 → merită citit (-(으)ㄹ 만하다)","en":"읽다 → worth reading (-(으)ㄹ 만하다)"},"options":["읽을 만해요","읽는 만해요","읽은 만해요","읽어 만해요"],"correct":"읽을 만해요"},
    {"lessonId":"T5-09","topik":5,"prompt":{"ro":"가다 → merită să mergi să vezi (가 보다 + -(으)ㄹ 만하다)","en":"가다 → worth going to see (가 보다 + -(으)ㄹ 만하다)"},"options":["가 볼 만해요","가는 볼 만해요","간 볼 만해요","가을 만해요"],"correct":"가 볼 만해요"},
    {"lessonId":"T5-10","topik":5,"prompt":{"ro":"자다 → a se preface că doarme (-는 척하다)","en":"자다 → to pretend to sleep (-는 척하다)"},"options":["자는 척했어요","잔 척했어요","자던 척했어요","잘 척했어요"],"correct":"자는 척했어요"},
    {"lessonId":"T5-10","topik":5,"prompt":{"ro":"바쁘다 → a se preface că e ocupat (adj + -(으)ㄴ 척하다)","en":"바쁘다 → to pretend to be busy (adj + -(으)ㄴ 척하다)"},"options":["바쁜 척했어요","바쁘는 척했어요","바쁠 척했어요","바빴는 척했어요"],"correct":"바쁜 척했어요"},
    {"lessonId":"T5-11","topik":5,"prompt":{"ro":"고프다 → probabil că ți-e foame (-(으)ㄹ 텐데)","en":"고프다 → you must be hungry (-(으)ㄹ 텐데)"},"options":["고플 텐데","고프을 텐데","고픈 텐데","고파 텐데"],"correct":"고플 텐데"},
    {"lessonId":"T5-11","topik":5,"prompt":{"ro":"있다 → ar trebui să poată face (할 수 있다 + -(으)ㄹ 텐데)","en":"있다 → should be able to do (할 수 있다 + -(으)ㄹ 텐데)"},"options":["할 수 있을 텐데요","할 수 있는 텐데요","할 수 있은 텐데요","할 수 있어 텐데요"],"correct":"할 수 있을 텐데요"},
]

new_puzzle = [
    {"lessonId":"T5-01","topik":5,"tiles":["늦잠을","안","바람에","알람이","잤어요","울리는"],"correct":["알람이","안","울리는","바람에","늦잠을","잤어요"],"hint":{"ro":"Din cauză că alarma nu a sunat, am dormit prea mult.","en":"Because the alarm didn't go off, I overslept."}},
    {"lessonId":"T5-01","topik":5,"tiles":["연락을","바람에","전화기가","못","고장","했어요","나는"],"correct":["전화기가","고장","나는","바람에","연락을","못","했어요"],"hint":{"ro":"Din cauză că telefonul s-a stricat, nu am putut lua legătura.","en":"Because my phone broke down, I couldn't contact anyone."}},
    {"lessonId":"T5-02","topik":5,"tiles":["뿐만","가격도","식당은","저렴해요","맛있을","아니라","이"],"correct":["이","식당은","맛있을","뿐만","아니라","가격도","저렴해요"],"hint":{"ro":"Acest restaurant nu este doar delicios, ci și prețul este accesibil.","en":"This restaurant is not only delicious, but the price is also cheap."}},
    {"lessonId":"T5-02","topik":5,"tiles":["해소에도","운동은","좋을","건강에","뿐만","도움이","아니라","스트레스","돼요"],"correct":["운동은","건강에","좋을","뿐만","아니라","스트레스","해소에도","도움이","돼요"],"hint":{"ro":"Sportul nu este doar bun pentru sănătate, ci ajută și la eliminarea stresului.","en":"Exercise is not only good for health, but also helps with stress relief."}},
    {"lessonId":"T5-03","topik":5,"tiles":["만들어졌어요","정부에","법은","이","의해"],"correct":["이","법은","정부에","의해","만들어졌어요"],"hint":{"ro":"Această lege a fost creată de guvern.","en":"This law was made by the government."}},
    {"lessonId":"T5-03","topik":5,"tiles":["개발됐어요","치료법이","의해","과학자들에","새로운"],"correct":["새로운","치료법이","과학자들에","의해","개발됐어요"],"hint":{"ro":"Un nou tratament a fost dezvoltat de oameni de știință.","en":"A new treatment was developed by scientists."}},
    {"lessonId":"T5-04","topik":5,"tiles":["책이에요","자주","학생","읽던","때"],"correct":["학생","때","자주","읽던","책이에요"],"hint":{"ro":"Aceasta este o carte pe care o citeam des pe când eram student.","en":"This is a book I often read when I was a student."}},
    {"lessonId":"T5-04","topik":5,"tiles":["만났어요","친구를","오랜만에","같이","놀던"],"correct":["같이","놀던","친구를","오랜만에","만났어요"],"hint":{"ro":"L-am întâlnit după mult timp pe prietenul cu care mă jucam.","en":"I met a friend I used to play with after a long time."}},
    {"lessonId":"T5-05","topik":5,"tiles":["시작했어요","보호하고자","캠페인을","환경을"],"correct":["환경을","보호하고자","캠페인을","시작했어요"],"hint":{"ro":"Am început o campanie cu intenția de a proteja mediul.","en":"We started a campaign with the intention of protecting the environment."}},
    {"lessonId":"T5-05","topik":5,"tiles":["연습합니다","향상시키고자","매일","실력을"],"correct":["실력을","향상시키고자","매일","연습합니다"],"hint":{"ro":"Exersez în fiecare zi cu intenția de a-mi îmbunătăți abilitățile.","en":"I practice every day with the intention of improving my skills."}},
    {"lessonId":"T5-06","topik":5,"tiles":["없어요","사람이","모를","그렇게","리가","똑똑한"],"correct":["그렇게","똑똑한","사람이","모를","리가","없어요"],"hint":{"ro":"Nu este posibil ca o persoană atât de inteligentă să nu știe.","en":"There's no way that such a smart person doesn't know."}},
    {"lessonId":"T5-06","topik":5,"tiles":["고플","밥을","방금","리가","배가","없어요","먹었는데"],"correct":["방금","밥을","먹었는데","배가","고플","리가","없어요"],"hint":{"ro":"Tocmai am mâncat, deci nu este posibil să îmi fie foame.","en":"I just ate, so there's no way I'm hungry."}},
    {"lessonId":"T5-07","topik":5,"tiles":["좋지","분위기가","느끼다시피","않아요","오늘"],"correct":["느끼다시피","오늘","분위기가","좋지","않아요"],"hint":{"ro":"Cum puteți simți, atmosfera de azi nu este bună.","en":"As you can feel, the atmosphere today is not good."}},
    {"lessonId":"T5-07","topik":5,"tiles":["않았어요","결과가","예상하다시피","좋지"],"correct":["예상하다시피","결과가","좋지","않았어요"],"hint":{"ro":"Cum era de așteptat, rezultatele nu au fost bune.","en":"As expected, the results were not good."}},
    {"lessonId":"T5-08","topik":5,"tiles":["실수를","않았더라면","말을","그","듣지","거예요","안","했을"],"correct":["그","말을","듣지","않았더라면","실수를","안","했을","거예요"],"hint":{"ro":"Dacă nu aș fi ascultat acele cuvinte, nu aș fi făcut greșeala.","en":"If I hadn't listened to those words, I wouldn't have made a mistake."}},
    {"lessonId":"T5-08","topik":5,"tiles":["좋았을","가져왔더라면","우산을","텐데"],"correct":["우산을","가져왔더라면","좋았을","텐데"],"hint":{"ro":"Ar fi fost bine dacă aș fi adus umbrela.","en":"It would have been good if I had brought an umbrella."}},
    {"lessonId":"T5-09","topik":5,"tiles":["만해요","책은","읽을","이"],"correct":["이","책은","읽을","만해요"],"hint":{"ro":"Această carte merită citită.","en":"This book is worth reading."}},
    {"lessonId":"T5-09","topik":5,"tiles":["만한","한번","가","곳이에요","볼"],"correct":["한번","가","볼","만한","곳이에요"],"hint":{"ro":"Este un loc care merită vizitat cel puțin o dată.","en":"It's a place worth visiting."}},
    {"lessonId":"T5-10","topik":5,"tiles":["들었어요","자는","이야기를","척하면서"],"correct":["자는","척하면서","이야기를","들었어요"],"hint":{"ro":"M-am prefăcut că dorm și am ascultat conversația.","en":"I pretended to sleep and listened to the conversation."}},
    {"lessonId":"T5-10","topik":5,"tiles":["전화를","척해서","바쁜","받았어요","안"],"correct":["바쁜","척해서","전화를","안","받았어요"],"hint":{"ro":"M-am prefăcut că sunt ocupat și nu am răspuns la telefon.","en":"I pretended to be busy and didn't answer the phone."}},
    {"lessonId":"T5-11","topik":5,"tiles":["밥","배가","같이","고플","먹어요","텐데"],"correct":["배가","고플","텐데","같이","밥","먹어요"],"hint":{"ro":"Probabil că ți-e foame, să mâncăm împreună.","en":"You must be hungry, let's eat together."}},
    {"lessonId":"T5-11","topik":5,"tiles":["텐데요","할","수","있을","어렵겠지만"],"correct":["어렵겠지만","할","수","있을","텐데요"],"hint":{"ro":"Poate fi greu, dar ar trebui să poți reuși.","en":"It might be difficult, but you should be able to do it."}},
]

new_chain = [
    {"lessonId":"T5-01","topik":5,"tiles":["그래서 오늘 학교에 지각했어요.","알람이 안 울리는 바람에 늦잠을 잤어요.","어젯밤에 피곤해서 일찍 잤어요.","선생님께 사과했어요."],"correct":["어젯밤에 피곤해서 일찍 잤어요.","알람이 안 울리는 바람에 늦잠을 잤어요.","그래서 오늘 학교에 지각했어요.","선생님께 사과했어요."],"context":{"ro":"O dimineață complicată","en":"A complicated morning"}},
    {"lessonId":"T5-01","topik":5,"tiles":["전화기가 고장 나는 바람에 연락을 못 했어요.","서비스센터에 가서 고쳤어요.","친구와 약속이 있었어요.","친구가 많이 기다렸어요."],"correct":["친구와 약속이 있었어요.","전화기가 고장 나는 바람에 연락을 못 했어요.","친구가 많이 기다렸어요.","서비스센터에 가서 고쳤어요."],"context":{"ro":"Telefon stricat și un prieten care așteaptă","en":"Broken phone and a waiting friend"}},
    {"lessonId":"T5-02","topik":5,"tiles":["이 식당은 맛있을 뿐만 아니라 가격도 저렴해요.","그래서 항상 손님이 많아요.","친구가 맛집을 추천해 줬어요.","다음에 또 오고 싶어요."],"correct":["친구가 맛집을 추천해 줬어요.","이 식당은 맛있을 뿐만 아니라 가격도 저렴해요.","그래서 항상 손님이 많아요.","다음에 또 오고 싶어요."],"context":{"ro":"Un restaurant recomandat","en":"A recommended restaurant"}},
    {"lessonId":"T5-02","topik":5,"tiles":["왜 운동을 시작했어요?","운동은 건강에 좋을 뿐만 아니라 스트레스 해소에도 도움이 돼요.","그래서 매일 운동하기로 했어요.","지금은 기분이 훨씬 좋아요."],"correct":["왜 운동을 시작했어요?","운동은 건강에 좋을 뿐만 아니라 스트레스 해소에도 도움이 돼요.","그래서 매일 운동하기로 했어요.","지금은 기분이 훨씬 좋아요."],"context":{"ro":"Beneficiile exercițiilor fizice","en":"Benefits of exercise"}},
    {"lessonId":"T5-03","topik":5,"tiles":["이 법은 정부에 의해 만들어졌어요.","많은 사람들이 이 법을 지지해요.","새로운 법이 필요했어요.","이제 더 안전한 사회가 됐어요."],"correct":["새로운 법이 필요했어요.","이 법은 정부에 의해 만들어졌어요.","많은 사람들이 이 법을 지지해요.","이제 더 안전한 사회가 됐어요."],"context":{"ro":"O lege nouă","en":"A new law"}},
    {"lessonId":"T5-03","topik":5,"tiles":["새로운 치료법이 과학자들에 의해 개발됐어요.","많은 환자들이 이 치료법으로 나았어요.","오래된 병이 있었어요.","앞으로 더 많은 연구가 필요해요."],"correct":["오래된 병이 있었어요.","새로운 치료법이 과학자들에 의해 개발됐어요.","많은 환자들이 이 치료법으로 나았어요.","앞으로 더 많은 연구가 필요해요."],"context":{"ro":"Descoperire medicală","en":"Medical discovery"}},
    {"lessonId":"T5-04","topik":5,"tiles":["학생 때 자주 읽던 책이에요.","그 때는 매일 책을 읽었어요.","오래된 책장에서 찾았어요.","지금도 재미있어요."],"correct":["오래된 책장에서 찾았어요.","학생 때 자주 읽던 책이에요.","그 때는 매일 책을 읽었어요.","지금도 재미있어요."],"context":{"ro":"O carte din trecut","en":"A book from the past"}},
    {"lessonId":"T5-04","topik":5,"tiles":["같이 놀던 친구를 오랜만에 만났어요.","서로 많이 바뀌었어요.","어릴 때 매일 같이 놀았어요.","옛날 이야기를 하며 즐거운 시간을 보냈어요."],"correct":["어릴 때 매일 같이 놀았어요.","같이 놀던 친구를 오랜만에 만났어요.","서로 많이 바뀌었어요.","옛날 이야기를 하며 즐거운 시간을 보냈어요."],"context":{"ro":"Reîntâlnire cu un vechi prieten","en":"Reunion with an old friend"}},
    {"lessonId":"T5-05","topik":5,"tiles":["환경을 보호하고자 캠페인을 시작했어요.","많은 사람들이 참여했어요.","우리 지역의 환경이 나빠지고 있었어요.","환경이 조금씩 좋아지고 있어요."],"correct":["우리 지역의 환경이 나빠지고 있었어요.","환경을 보호하고자 캠페인을 시작했어요.","많은 사람들이 참여했어요.","환경이 조금씩 좋아지고 있어요."],"context":{"ro":"Campanie pentru mediu","en":"Environmental campaign"}},
    {"lessonId":"T5-05","topik":5,"tiles":["실력을 향상시키고자 매일 연습합니다.","처음에는 잘 못 했어요.","한국어를 잘 하고 싶어요.","이제 실력이 많이 늘었어요."],"correct":["한국어를 잘 하고 싶어요.","실력을 향상시키고자 매일 연습합니다.","처음에는 잘 못 했어요.","이제 실력이 많이 늘었어요."],"context":{"ro":"Îmbunătățind abilități","en":"Improving skills"}},
    {"lessonId":"T5-06","topik":5,"tiles":["그렇게 똑똑한 사람이 모를 리가 없어요.","왜 대답을 안 할까요?","그분은 이 분야의 전문가예요.","아마 다른 이유가 있을 거예요."],"correct":["그분은 이 분야의 전문가예요.","그렇게 똑똑한 사람이 모를 리가 없어요.","왜 대답을 안 할까요?","아마 다른 이유가 있을 거예요."],"context":{"ro":"Un expert care tace","en":"An expert who stays silent"}},
    {"lessonId":"T5-06","topik":5,"tiles":["방금 밥을 먹었는데 배가 고플 리가 없어요.","그런데 왜 또 먹고 싶을까요?","아까 점심을 먹었어요.","아마 그냥 입이 심심한 거겠죠."],"correct":["아까 점심을 먹었어요.","방금 밥을 먹었는데 배가 고플 리가 없어요.","그런데 왜 또 먹고 싶을까요?","아마 그냥 입이 심심한 거겠죠."],"context":{"ro":"Poftă de mâncare fără foame","en":"Craving food without being hungry"}},
    {"lessonId":"T5-07","topik":5,"tiles":["느끼다시피 오늘 분위기가 좋지 않아요.","무슨 일이 있었나요?","모두가 조용하고 긴장해 보여요.","나중에 이야기해 볼게요."],"correct":["모두가 조용하고 긴장해 보여요.","느끼다시피 오늘 분위기가 좋지 않아요.","무슨 일이 있었나요?","나중에 이야기해 볼게요."],"context":{"ro":"Atmosferă tensionată","en":"Tense atmosphere"}},
    {"lessonId":"T5-07","topik":5,"tiles":["예상하다시피 결과가 좋지 않았어요.","다음에는 더 잘 준비해야 해요.","모두 열심히 했지만 어려웠어요.","포기하지 않고 다시 도전할 거예요."],"correct":["모두 열심히 했지만 어려웠어요.","예상하다시피 결과가 좋지 않았어요.","다음에는 더 잘 준비해야 해요.","포기하지 않고 다시 도전할 거예요."],"context":{"ro":"Rezultate dezamăgitoare","en":"Disappointing results"}},
    {"lessonId":"T5-08","topik":5,"tiles":["그 말을 듣지 않았더라면 실수를 안 했을 거예요.","앞으로는 더 신중하게 결정할 거예요.","친구의 말을 믿고 따라 했어요.","결국 문제가 생겼어요."],"correct":["친구의 말을 믿고 따라 했어요.","그 말을 듣지 않았더라면 실수를 안 했을 거예요.","결국 문제가 생겼어요.","앞으로는 더 신중하게 결정할 거예요."],"context":{"ro":"Regret după un sfat rău","en":"Regret after bad advice"}},
    {"lessonId":"T5-08","topik":5,"tiles":["우산을 가져왔더라면 좋았을 텐데.","집에 돌아오니 옷이 다 젖었어요.","나올 때 날씨가 맑았어요.","갑자기 비가 왔어요."],"correct":["나올 때 날씨가 맑았어요.","갑자기 비가 왔어요.","우산을 가져왔더라면 좋았을 텐데.","집에 돌아오니 옷이 다 젖었어요."],"context":{"ro":"Prins în ploaie fără umbrelă","en":"Caught in the rain without an umbrella"}},
    {"lessonId":"T5-09","topik":5,"tiles":["이 책은 읽을 만해요.","주말에 다 읽었어요.","친구가 추천해 줬어요.","정말 재미있었어요."],"correct":["친구가 추천해 줬어요.","이 책은 읽을 만해요.","주말에 다 읽었어요.","정말 재미있었어요."],"context":{"ro":"O carte recomandată","en":"A recommended book"}},
    {"lessonId":"T5-09","topik":5,"tiles":["한번 가 볼 만한 곳이에요.","경치가 정말 아름다웠어요.","여행 블로그에서 봤어요.","꼭 다시 가고 싶어요."],"correct":["여행 블로그에서 봤어요.","한번 가 볼 만한 곳이에요.","경치가 정말 아름다웠어요.","꼭 다시 가고 싶어요."],"context":{"ro":"Un loc care merită vizitat","en":"A place worth visiting"}},
    {"lessonId":"T5-10","topik":5,"tiles":["자는 척하면서 이야기를 들었어요.","형이 제 얘기를 하고 있었어요.","자는 것처럼 눈을 감았어요.","나중에 모두 알게 됐어요."],"correct":["자는 것처럼 눈을 감았어요.","자는 척하면서 이야기를 들었어요.","형이 제 얘기를 하고 있었어요.","나중에 모두 알게 됐어요."],"context":{"ro":"Prefăcut că doarme","en":"Pretending to sleep"}},
    {"lessonId":"T5-10","topik":5,"tiles":["바쁜 척해서 전화를 안 받았어요.","나중에 죄송하다고 사과했어요.","받기 싫은 전화가 왔어요.","전화를 안 받으면 안 될 것 같았어요."],"correct":["받기 싫은 전화가 왔어요.","바쁜 척해서 전화를 안 받았어요.","전화를 안 받으면 안 될 것 같았어요.","나중에 죄송하다고 사과했어요."],"context":{"ro":"Evitând un apel telefonic","en":"Avoiding a phone call"}},
    {"lessonId":"T5-11","topik":5,"tiles":["배가 고플 텐데 같이 밥 먹어요.","감사해요, 배가 많이 고팠어요.","오랫동안 아무것도 안 먹었네요.","맛있게 먹었어요."],"correct":["오랫동안 아무것도 안 먹었네요.","배가 고플 텐데 같이 밥 먹어요.","감사해요, 배가 많이 고팠어요.","맛있게 먹었어요."],"context":{"ro":"Invitație la masă","en":"An invitation to eat"}},
    {"lessonId":"T5-11","topik":5,"tiles":["어렵겠지만 할 수 있을 텐데요.","정말요? 자신이 없어요.","이 일은 쉽지 않아요.","한 번 해 보세요. 충분히 할 수 있어요."],"correct":["이 일은 쉽지 않아요.","어렵겠지만 할 수 있을 텐데요.","정말요? 자신이 없어요.","한 번 해 보세요. 충분히 할 수 있어요."],"context":{"ro":"Încurajare pentru o sarcină dificilă","en":"Encouragement for a difficult task"}},
]

data['ko-ro'].extend(new_ko_ro)
data['ro-ko'].extend(new_ro_ko)
data['particle'].extend(new_particle)
data['particlePlus'].extend(new_particle_plus)
data['conjug'].extend(new_conjug)
data['puzzle'].extend(new_puzzle)
data['chain'].extend(new_chain)

with open('data/exercises.json', 'w', encoding='utf-8') as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

print("Done! New counts:")
print({k: len(v) for k, v in data.items()})
