import json

with open('data/exercises.json', 'r', encoding='utf-8') as f:
    data = json.load(f)

new_ko_ro = [
    {"lessonId":"T6-01","topik":6,"q":"한국어를 공부하다 보니 정말 재미있더라고요.","answers":{"ro":["Pe măsură ce studiam coreana, mi-am dat seama că e cu adevărat interesantă.","Coreana este prea grea de studiat.","Nu am găsit coreana interesantă.","Am încetat să studiez coreana."],"en":["As I kept studying Korean, I found it was really interesting.","Korean is too hard to study.","I didn't find Korean interesting.","I stopped studying Korean."]},"correct":{"ro":"Pe măsură ce studiam coreana, mi-am dat seama că e cu adevărat interesantă.","en":"As I kept studying Korean, I found it was really interesting."}},
    {"lessonId":"T6-01","topik":6,"q":"그 영화 정말 감동적이더라고요.","answers":{"ro":["Am descoperit că filmul acela e cu adevărat emoționant.","Filmul nu mi-a plăcut deloc.","Filmul era plictisitor.","Nu am văzut filmul."],"en":["That movie turned out to be really touching.","I didn't like that movie at all.","The movie was boring.","I haven't seen the movie."]},"correct":{"ro":"Am descoperit că filmul acela e cu adevărat emoționant.","en":"That movie turned out to be really touching."}},
    {"lessonId":"T6-02","topik":6,"q":"두 언어를 알면 기회가 두 배로 생기는 셈이에요.","answers":{"ro":["Dacă știi două limbi, practic ți se dublează oportunitățile.","O singură limbă e suficientă.","Limbile nu oferă oportunități.","Două limbi sunt prea multe de învățat."],"en":["If you know two languages, it practically means your opportunities double.","One language is enough.","Languages don't provide opportunities.","Two languages are too many to learn."]},"correct":{"ro":"Dacă știi două limbi, practic ți se dublează oportunitățile.","en":"If you know two languages, it practically means your opportunities double."}},
    {"lessonId":"T6-02","topik":6,"q":"매일 조금씩 저축하면 1년 후엔 꽤 모이는 셈이에요.","answers":{"ro":["Dacă economisești câte puțin în fiecare zi, după un an se adună destul de mult.","Nu are rost să economisești puțin.","Un an e prea puțin pentru economii.","Este mai bine să cheltuiești totul."],"en":["If you save a little every day, after a year it practically adds up to quite a lot.","There's no point in saving a little.","A year is too short for savings.","It's better to spend everything."]},"correct":{"ro":"Dacă economisești câte puțin în fiecare zi, după un an se adună destul de mult.","en":"If you save a little every day, after a year it practically adds up to quite a lot."}},
    {"lessonId":"T6-03","topik":6,"q":"스트레스로 인해 건강이 나빠질 수 있어요.","answers":{"ro":["Din cauza stresului, sănătatea se poate înrăutăți.","Stresul îmbunătățește sănătatea.","Sănătatea nu este afectată de stres.","Stresul nu are niciun efect."],"en":["Due to stress, health can deteriorate.","Stress improves health.","Health is not affected by stress.","Stress has no effect."]},"correct":{"ro":"Din cauza stresului, sănătatea se poate înrăutăți.","en":"Due to stress, health can deteriorate."}},
    {"lessonId":"T6-03","topik":6,"q":"인터넷의 발달로 인해 정보를 쉽게 얻을 수 있게 됐어요.","answers":{"ro":["Datorită dezvoltării internetului, a devenit posibil să obținem informații cu ușurință.","Internetul a îngreunat accesul la informații.","Nu folosim internetul pentru informații.","Internetul nu s-a dezvoltat deloc."],"en":["Due to the development of the internet, it became easy to obtain information.","The internet made accessing information harder.","We don't use the internet for information.","The internet hasn't developed at all."]},"correct":{"ro":"Datorită dezvoltării internetului, a devenit posibil să obținem informații cu ușurință.","en":"Due to the development of the internet, it became easy to obtain information."}},
    {"lessonId":"T6-04","topik":6,"q":"이것은 제 의견에 불과합니다.","answers":{"ro":["Aceasta nu este altceva decât opinia mea.","Aceasta este o opinie oficială.","Toată lumea gândește la fel.","Opinia mea este corectă cu siguranță."],"en":["This is nothing more than my opinion.","This is an official opinion.","Everyone thinks the same way.","My opinion is definitely correct."]},"correct":{"ro":"Aceasta nu este altceva decât opinia mea.","en":"This is nothing more than my opinion."}},
    {"lessonId":"T6-04","topik":6,"q":"그 이유는 핑계에 불과했어요.","answers":{"ro":["Acel motiv nu era altceva decât o scuză.","Acel motiv era cu adevărat valid.","Nu a oferit niciun motiv.","Motivul era convingător."],"en":["That reason was nothing more than an excuse.","That reason was truly valid.","No reason was given.","The reason was convincing."]},"correct":{"ro":"Acel motiv nu era altceva decât o scuză.","en":"That reason was nothing more than an excuse."}},
    {"lessonId":"T6-05","topik":6,"q":"너무 배가 고파서 쓰러질 지경이에요.","answers":{"ro":["Mi-e atât de foame că aproape leșin.","Nu mi-e foame deloc.","Am mâncat prea mult.","Mi-e un pic foame."],"en":["I'm so hungry I'm almost about to faint.","I'm not hungry at all.","I ate too much.","I'm a little hungry."]},"correct":{"ro":"Mi-e atât de foame că aproape leșin.","en":"I'm so hungry I'm almost about to faint."}},
    {"lessonId":"T6-05","topik":6,"q":"시험 스트레스로 울 지경이에요.","answers":{"ro":["Din cauza stresului de la examene, sunt pe punctul de a plânge.","Nu sunt deloc stresat/stresată de examene.","Îmi plac examenele.","Examenele sunt ușoare."],"en":["Due to exam stress, I'm almost at the point of crying.","I'm not stressed about exams at all.","I like exams.","Exams are easy."]},"correct":{"ro":"Din cauza stresului de la examene, sunt pe punctul de a plânge.","en":"Due to exam stress, I'm almost at the point of crying."}},
    {"lessonId":"T6-06","topik":6,"q":"너무 웃은 나머지 배가 아팠어요.","answers":{"ro":["Ca urmare a râsului excesiv, m-a durut burta.","Nu am râs deloc.","M-am supărat pentru că am râs.","Burta mă doare din altă cauză."],"en":["As a result of laughing too much, my stomach hurt.","I didn't laugh at all.","I got angry from laughing.","My stomach hurts for another reason."]},"correct":{"ro":"Ca urmare a râsului excesiv, m-a durut burta.","en":"As a result of laughing too much, my stomach hurt."}},
    {"lessonId":"T6-06","topik":6,"q":"걱정한 나머지 밤새 잠을 못 잤어요.","answers":{"ro":["Ca urmare a îngrijorării excesive, nu am putut dormi toată noaptea.","Am dormit bine în ciuda îngrijorării.","Nu m-am îngrijorat deloc.","M-am culcat devreme."],"en":["As a result of worrying too much, I couldn't sleep all night.","I slept well despite the worry.","I didn't worry at all.","I went to bed early."]},"correct":{"ro":"Ca urmare a îngrijorării excesive, nu am putut dormi toată noaptea.","en":"As a result of worrying too much, I couldn't sleep all night."}},
    {"lessonId":"T6-07","topik":6,"q":"그저 감사할 따름이에요.","answers":{"ro":["Tot ce pot face este să fiu recunoscător/recunoscătoare.","Nu sunt deloc recunoscător/recunoscătoare.","Nu am motive să fiu recunoscător.","Sunt supărat/supărată, nu recunoscător."],"en":["All I can do is be grateful.","I'm not grateful at all.","I have no reason to be grateful.","I'm upset, not grateful."]},"correct":{"ro":"Tot ce pot face este să fiu recunoscător/recunoscătoare.","en":"All I can do is be grateful."}},
    {"lessonId":"T6-07","topik":6,"q":"묵묵히 앞으로 나아갈 따름입니다.","answers":{"ro":["Tot ce pot face este să merg înainte în tăcere.","Vreau să mă opresc și să mă odihnesc.","Nu știu ce direcție să iau.","Am renunțat la drum."],"en":["All I can do is silently move forward.","I want to stop and rest.","I don't know which direction to take.","I've given up on the journey."]},"correct":{"ro":"Tot ce pot face este să merg înainte în tăcere.","en":"All I can do is silently move forward."}},
    {"lessonId":"T6-08","topik":6,"q":"연습하면 실력이 늘기 마련이에요.","answers":{"ro":["E firesc ca dacă exersezi, nivelul să crească.","Exersatul nu ajută la nimic.","Nivelul scade cu cât exersezi.","Nu trebuie să exersezi."],"en":["It's natural that if you practice, your skills will improve.","Practicing doesn't help at all.","Your skills decrease the more you practice.","You don't need to practice."]},"correct":{"ro":"E firesc ca dacă exersezi, nivelul să crească.","en":"It's natural that if you practice, your skills will improve."}},
    {"lessonId":"T6-08","topik":6,"q":"좋은 일 뒤에는 힘든 일도 있기 마련이에요.","answers":{"ro":["E firesc că după lucruri bune, să urmeze și lucruri grele.","După lucruri bune urmează numai lucruri bune.","Lucrurile grele nu se întâmplă niciodată.","Nu există lucruri bune în viață."],"en":["It's natural that after good things, difficult things also follow.","After good things, only good things follow.","Difficult things never happen.","There are no good things in life."]},"correct":{"ro":"E firesc că după lucruri bune, să urmeze și lucruri grele.","en":"It's natural that after good things, difficult things also follow."}},
]

new_ro_ko = [
    {"lessonId":"T6-01","topik":6,"prompt":{"ro":"Pe măsură ce studiam coreana, mi-am dat seama că e cu adevărat interesantă.","en":"As I kept studying Korean, I found it was really interesting."},"options":["한국어를 공부하다 보니 정말 재미있더라고요.","한국어가 너무 어렵더라고요.","한국어를 공부하고 싶어요.","한국어를 포기했어요."],"correct":"한국어를 공부하다 보니 정말 재미있더라고요."},
    {"lessonId":"T6-01","topik":6,"prompt":{"ro":"Am descoperit că filmul acela e cu adevărat emoționant.","en":"That movie turned out to be really touching."},"options":["그 영화 정말 감동적이더라고요.","그 영화가 재미없더라고요.","그 영화를 아직 안 봤어요.","그 영화는 무서웠어요."],"correct":"그 영화 정말 감동적이더라고요."},
    {"lessonId":"T6-02","topik":6,"prompt":{"ro":"Dacă știi două limbi, practic ți se dublează oportunitățile.","en":"If you know two languages, it practically means your opportunities double."},"options":["두 언어를 알면 기회가 두 배로 생기는 셈이에요.","두 언어는 배우기 너무 어려워요.","언어는 필요 없어요.","한 언어만으로 충분해요."],"correct":"두 언어를 알면 기회가 두 배로 생기는 셈이에요."},
    {"lessonId":"T6-02","topik":6,"prompt":{"ro":"Dacă economisești câte puțin în fiecare zi, după un an se adună destul de mult.","en":"If you save a little every day, after a year it practically adds up to quite a lot."},"options":["매일 조금씩 저축하면 1년 후엔 꽤 모이는 셈이에요.","저축은 의미가 없어요.","돈을 많이 써야 해요.","1년 후엔 아무것도 안 모여요."],"correct":"매일 조금씩 저축하면 1년 후엔 꽤 모이는 셈이에요."},
    {"lessonId":"T6-03","topik":6,"prompt":{"ro":"Din cauza stresului, sănătatea se poate înrăutăți.","en":"Due to stress, health can deteriorate."},"options":["스트레스로 인해 건강이 나빠질 수 있어요.","스트레스로 건강이 좋아져요.","스트레스가 없어요.","건강은 스트레스와 관계없어요."],"correct":"스트레스로 인해 건강이 나빠질 수 있어요."},
    {"lessonId":"T6-03","topik":6,"prompt":{"ro":"Datorită dezvoltării internetului, a devenit posibil să obținem informații cu ușurință.","en":"Due to the development of the internet, it became easy to obtain information."},"options":["인터넷의 발달로 인해 정보를 쉽게 얻을 수 있게 됐어요.","인터넷이 정보 얻기를 어렵게 했어요.","인터넷을 정보에 사용 안 해요.","인터넷은 발달하지 않았어요."],"correct":"인터넷의 발달로 인해 정보를 쉽게 얻을 수 있게 됐어요."},
    {"lessonId":"T6-04","topik":6,"prompt":{"ro":"Aceasta nu este altceva decât opinia mea.","en":"This is nothing more than my opinion."},"options":["이것은 제 의견에 불과합니다.","이것은 공식 의견입니다.","모두 같은 의견이에요.","제 의견이 항상 맞아요."],"correct":"이것은 제 의견에 불과합니다."},
    {"lessonId":"T6-04","topik":6,"prompt":{"ro":"Acel motiv nu era altceva decât o scuză.","en":"That reason was nothing more than an excuse."},"options":["그 이유는 핑계에 불과했어요.","그 이유는 진짜였어요.","이유를 말하지 않았어요.","이유가 설득력 있었어요."],"correct":"그 이유는 핑계에 불과했어요."},
    {"lessonId":"T6-05","topik":6,"prompt":{"ro":"Mi-e atât de foame că aproape leșin.","en":"I'm so hungry I'm almost about to faint."},"options":["너무 배가 고파서 쓰러질 지경이에요.","배가 전혀 안 고파요.","너무 많이 먹었어요.","조금 배가 고파요."],"correct":"너무 배가 고파서 쓰러질 지경이에요."},
    {"lessonId":"T6-05","topik":6,"prompt":{"ro":"Din cauza stresului de la examene, sunt pe punctul de a plânge.","en":"Due to exam stress, I'm almost at the point of crying."},"options":["시험 스트레스로 울 지경이에요.","시험이 전혀 걱정 안 돼요.","시험이 좋아요.","시험이 쉬워요."],"correct":"시험 스트레스로 울 지경이에요."},
    {"lessonId":"T6-06","topik":6,"prompt":{"ro":"Ca urmare a râsului excesiv, m-a durut burta.","en":"As a result of laughing too much, my stomach hurt."},"options":["너무 웃은 나머지 배가 아팠어요.","전혀 웃지 않았어요.","웃어서 화가 났어요.","배가 다른 이유로 아팠어요."],"correct":"너무 웃은 나머지 배가 아팠어요."},
    {"lessonId":"T6-06","topik":6,"prompt":{"ro":"Ca urmare a îngrijorării excesive, nu am putut dormi toată noaptea.","en":"As a result of worrying too much, I couldn't sleep all night."},"options":["걱정한 나머지 밤새 잠을 못 잤어요.","걱정했지만 잘 잤어요.","걱정하지 않았어요.","일찍 잠이 들었어요."],"correct":"걱정한 나머지 밤새 잠을 못 잤어요."},
    {"lessonId":"T6-07","topik":6,"prompt":{"ro":"Tot ce pot face este să fiu recunoscător/recunoscătoare.","en":"All I can do is be grateful."},"options":["그저 감사할 따름이에요.","전혀 감사하지 않아요.","감사할 이유가 없어요.","감사보다 화가 나요."],"correct":"그저 감사할 따름이에요."},
    {"lessonId":"T6-07","topik":6,"prompt":{"ro":"Tot ce pot face este să merg înainte în tăcere.","en":"All I can do is silently move forward."},"options":["묵묵히 앞으로 나아갈 따름입니다.","쉬고 싶어요.","어떤 방향으로 가야 할지 모르겠어요.","포기하기로 했어요."],"correct":"묵묵히 앞으로 나아갈 따름입니다."},
    {"lessonId":"T6-08","topik":6,"prompt":{"ro":"E firesc ca dacă exersezi, nivelul să crească.","en":"It's natural that if you practice, your skills will improve."},"options":["연습하면 실력이 늘기 마련이에요.","연습은 도움이 안 돼요.","연습할수록 실력이 줄어요.","연습할 필요 없어요."],"correct":"연습하면 실력이 늘기 마련이에요."},
    {"lessonId":"T6-08","topik":6,"prompt":{"ro":"E firesc că după lucruri bune, să urmeze și lucruri grele.","en":"It's natural that after good things, difficult things also follow."},"options":["좋은 일 뒤에는 힘든 일도 있기 마련이에요.","좋은 일 뒤에는 좋은 일만 와요.","힘든 일은 절대 없어요.","좋은 일은 없어요."],"correct":"좋은 일 뒤에는 힘든 일도 있기 마련이에요."},
]

new_particle = [
    {"lessonId":"T6-01","topik":6,"template":"한국어___ 공부하다 보니 정말 재미있더라고요.","options":["를","이","은","도"],"correct":"를","hint":{"ro":"Complement direct: 한국어 — se termină în vocală → 를","en":"Object: 한국어 — ends in vowel → 를"}},
    {"lessonId":"T6-01","topik":6,"template":"그 영화___ 정말 감동적이더라고요.","options":["는","이","를","에"],"correct":"는","hint":{"ro":"Topic: 영화 — se termină în vocală → 는","en":"Topic: 영화 — ends in vowel → 는"}},
    {"lessonId":"T6-02","topik":6,"template":"두 언어를 알면 기회___ 두 배로 생기는 셈이에요.","options":["가","를","는","이"],"correct":"가","hint":{"ro":"Subiect: 기회 — se termină în vocală → 가","en":"Subject: 기회 — ends in vowel → 가"}},
    {"lessonId":"T6-02","topik":6,"template":"매일 돈___ 조금씩 저축하면 1년 후엔 꽤 모이는 셈이에요.","options":["을","이","는","에"],"correct":"을","hint":{"ro":"Complement direct: 돈 — se termină în consoană → 을","en":"Object: 돈 — ends in consonant → 을"}},
    {"lessonId":"T6-03","topik":6,"template":"스트레스로 인해 건강___ 나빠질 수 있어요.","options":["이","가","을","도"],"correct":"이","hint":{"ro":"Subiect: 건강 — se termină în consoană → 이","en":"Subject: 건강 — ends in consonant → 이"}},
    {"lessonId":"T6-03","topik":6,"template":"인터넷의 발달로 인해 정보___ 쉽게 얻을 수 있게 됐어요.","options":["를","이","은","에"],"correct":"를","hint":{"ro":"Complement direct: 정보 — se termină în vocală → 를","en":"Object: 정보 — ends in vowel → 를"}},
    {"lessonId":"T6-04","topik":6,"template":"이것은 제 의견___ 불과합니다.","options":["에","이","를","도"],"correct":"에","hint":{"ro":"에 불과하다 = nu este decât (particulă fixă 에)","en":"에 불과하다 = nothing more than (fixed particle 에)"}},
    {"lessonId":"T6-04","topik":6,"template":"그 이유___ 핑계에 불과했어요.","options":["는","이","를","에"],"correct":"는","hint":{"ro":"Topic: 이유 — se termină în vocală → 는","en":"Topic: 이유 — ends in vowel → 는"}},
    {"lessonId":"T6-05","topik":6,"template":"너무 배___ 고파서 쓰러질 지경이에요.","options":["가","는","이","를"],"correct":"가","hint":{"ro":"Subiect: 배 (burtă) — se termină în vocală → 가","en":"Subject: 배 (stomach) — ends in vowel → 가"}},
    {"lessonId":"T6-05","topik":6,"template":"시험 스트레스___ 울 지경이에요.","options":["로","가","를","이"],"correct":"로","hint":{"ro":"스트레스로 = din cauza stresului (particulă cauză 로)","en":"스트레스로 = due to stress (cause particle 로)"}},
    {"lessonId":"T6-06","topik":6,"template":"너무 웃은 나머지 배___ 아팠어요.","options":["가","는","이","를"],"correct":"가","hint":{"ro":"Subiect: 배 — se termină în vocală → 가","en":"Subject: 배 — ends in vowel → 가"}},
    {"lessonId":"T6-06","topik":6,"template":"걱정한 나머지 밤새 잠___ 못 잤어요.","options":["을","이","는","에"],"correct":"을","hint":{"ro":"잠을 자다 = a dormi — complement direct: 잠 → 을","en":"잠을 자다 = to sleep — object: 잠 → 을"}},
    {"lessonId":"T6-07","topik":6,"template":"그저 감사한 마음___ 전할 따름이에요.","options":["을","이","는","에"],"correct":"을","hint":{"ro":"Complement direct: 마음 — se termină în consoană → 을","en":"Object: 마음 — ends in consonant → 을"}},
    {"lessonId":"T6-07","topik":6,"template":"우리___ 묵묵히 앞으로 나아갈 따름입니다.","options":["는","이","를","에"],"correct":"는","hint":{"ro":"Topic: 우리 — se termină în vocală → 는","en":"Topic: 우리 — ends in vowel → 는"}},
    {"lessonId":"T6-08","topik":6,"template":"연습하면 실력___ 늘기 마련이에요.","options":["이","가","을","도"],"correct":"이","hint":{"ro":"Subiect: 실력 — se termină în consoană → 이","en":"Subject: 실력 — ends in consonant → 이"}},
    {"lessonId":"T6-08","topik":6,"template":"좋은 일 뒤에는 힘든 일___ 있기 마련이에요.","options":["도","이","를","에"],"correct":"도","hint":{"ro":"힘든 일도 = și lucruri grele (도 = și/de asemenea)","en":"힘든 일도 = also difficult things (도 = also)"}},
]

new_particle_plus = [
    {"lessonId":"T6-01","topik":6,"template":"한국어___ 공부하다 보니 정말 재미있고 일본어___ 배우고 싶어졌어요.","options":[["를","도"],["이","도"],["를","가"],["는","도"]],"correct":["를","도"],"hint":{"ro":"한국어 (vocală→를, obiect), 일본어도 = și japoneza (도)","en":"한국어 (vowel→를, object), 일본어도 = also Japanese (도)"}},
    {"lessonId":"T6-01","topik":6,"template":"그 영화___ 정말 감동적이고 음악___ 아름다웠더라고요.","options":[["가","도"],["는","도"],["가","이"],["이","도"]],"correct":["가","도"],"hint":{"ro":"영화 (vocală→가, subiect), 음악도 = și muzica (도)","en":"영화 (vowel→가, subject), 음악도 = also the music (도)"}},
    {"lessonId":"T6-02","topik":6,"template":"두 언어___ 알면 기회___ 두 배로 생기는 셈이에요.","options":[["를","가"],["이","가"],["를","이"],["를","는"]],"correct":["를","가"],"hint":{"ro":"언어 (vocală→를, obiect), 기회 (vocală→가, subiect)","en":"언어 (vowel→를, object), 기회 (vowel→가, subject)"}},
    {"lessonId":"T6-02","topik":6,"template":"매일 돈___ 조금씩 저축하면 나중___ 꽤 모이는 셈이에요.","options":[["을","에"],["이","에"],["를","에"],["을","는"]],"correct":["을","에"],"hint":{"ro":"돈 (consoană→을, obiect), 나중에 = mai târziu (에 timp)","en":"돈 (consonant→을, object), 나중에 = later (에 time)"}},
    {"lessonId":"T6-03","topik":6,"template":"스트레스___ 인해 건강___ 나빠질 수 있어요.","options":[["로","이"],["가","이"],["로","가"],["이","이"]],"correct":["로","이"],"hint":{"ro":"스트레스로 인해 = din cauza stresului (로 fix), 건강 (consoană→이, subiect)","en":"스트레스로 인해 = due to stress (fixed 로), 건강 (consonant→이, subject)"}},
    {"lessonId":"T6-03","topik":6,"template":"인터넷의 발달___ 인해 정보___ 쉽게 얻을 수 있게 됐어요.","options":[["로","를"],["이","를"],["로","을"],["가","를"]],"correct":["로","를"],"hint":{"ro":"발달로 인해 = datorită dezvoltării (로 fix), 정보 (vocală→를, obiect)","en":"발달로 인해 = due to development (fixed 로), 정보 (vowel→를, object)"}},
    {"lessonId":"T6-04","topik":6,"template":"이것___ 제 의견___ 불과합니다.","options":[["은","에"],["이","에"],["는","에"],["를","에"]],"correct":["은","에"],"hint":{"ro":"이것 (consoană→은, topic), 의견에 불과하다 = nu e decât opinia (에 fix)","en":"이것 (consonant→은, topic), 의견에 불과하다 = nothing but opinion (fixed 에)"}},
    {"lessonId":"T6-04","topik":6,"template":"그 이유___ 핑계___ 불과했어요.","options":[["는","에"],["이","에"],["를","에"],["은","에"]],"correct":["는","에"],"hint":{"ro":"이유 (vocală→는, topic), 핑계에 불과하다 = nu e decât o scuză (에 fix)","en":"이유 (vowel→는, topic), 핑계에 불과하다 = nothing but excuse (fixed 에)"}},
    {"lessonId":"T6-05","topik":6,"template":"너무 배___ 고파서 몸___ 쓰러질 지경이에요.","options":[["가","이"],["는","이"],["가","가"],["이","이"]],"correct":["가","이"],"hint":{"ro":"배 (vocală→가, subiect), 몸 (consoană→이, subiect)","en":"배 (vowel→가, subject), 몸 (consonant→이, subject)"}},
    {"lessonId":"T6-05","topik":6,"template":"스트레스___ 많아서 시험___ 앞두고 울 지경이에요.","options":[["가","을"],["이","을"],["가","를"],["가","이"]],"correct":["가","을"],"hint":{"ro":"스트레스 (vocală→가, subiect), 시험 (consoană→을, obiect)","en":"스트레스 (vowel→가, subject), 시험 (consonant→을, object)"}},
    {"lessonId":"T6-06","topik":6,"template":"너무 웃은 나머지 배___ 아프고 눈물___ 났어요.","options":[["가","도"],["는","도"],["가","이"],["이","도"]],"correct":["가","도"],"hint":{"ro":"배 (vocală→가, subiect), 눈물도 = și lacrimi (도)","en":"배 (vowel→가, subject), 눈물도 = also tears (도)"}},
    {"lessonId":"T6-06","topik":6,"template":"걱정한 나머지 밤새 잠___ 못 자고 식사___ 못 했어요.","options":[["을","도"],["이","도"],["를","도"],["을","는"]],"correct":["을","도"],"hint":{"ro":"잠 (consoană→을, obiect), 식사도 = și masa (도)","en":"잠 (consonant→을, object), 식사도 = also meals (도)"}},
    {"lessonId":"T6-07","topik":6,"template":"우리___ 그저 마음___ 전할 따름이에요.","options":[["는","을"],["이","을"],["는","를"],["가","을"]],"correct":["는","을"],"hint":{"ro":"우리 (vocală→는, topic), 마음 (consoană→을, obiect)","en":"우리 (vowel→는, topic), 마음 (consonant→을, object)"}},
    {"lessonId":"T6-07","topik":6,"template":"모두___ 최선을 다하고 결과___ 기다릴 따름입니다.","options":[["가","를"],["이","를"],["가","을"],["는","를"]],"correct":["가","를"],"hint":{"ro":"모두 (vocală→가, subiect), 결과 (vocală→를, obiect)","en":"모두 (vowel→가, subject), 결과 (vowel→를, object)"}},
    {"lessonId":"T6-08","topik":6,"template":"연습하면 실력___ 늘고 자신감___ 생기기 마련이에요.","options":[["이","도"],["가","도"],["이","는"],["을","도"]],"correct":["이","도"],"hint":{"ro":"실력 (consoană→이, subiect), 자신감도 = și încrederea (도)","en":"실력 (consonant→이, subject), 자신감도 = also confidence (도)"}},
    {"lessonId":"T6-08","topik":6,"template":"사람___ 좋은 일 뒤에 힘든 일___ 겪기 마련이에요.","options":[["은","을"],["이","을"],["은","를"],["가","을"]],"correct":["은","을"],"hint":{"ro":"사람 (consoană→은, topic), 일 (consoană→을, obiect)","en":"사람 (consonant→은, topic), 일 (consonant→을, object)"}},
]

new_conjug = [
    {"lessonId":"T6-01","topik":6,"prompt":{"ro":"재미있다 → am descoperit că e interesant (-더라고요, adj)","en":"재미있다 → I found it was interesting (-더라고요, adj)"},"options":["재미있더라고요","재미있었더라고요","재미있는더라고요","재미있을더라고요"],"correct":"재미있더라고요"},
    {"lessonId":"T6-01","topik":6,"prompt":{"ro":"감동적이다 → am descoperit că e emoționant (-더라고요)","en":"감동적이다 → I found it was touching (-더라고요)"},"options":["감동적이더라고요","감동적었더라고요","감동적이었더라고요","감동적더라고요"],"correct":"감동적이더라고요"},
    {"lessonId":"T6-02","topik":6,"prompt":{"ro":"생기다 → practic apar/se creează (-는 셈이다)","en":"생기다 → practically arise/are created (-는 셈이다)"},"options":["생기는 셈이에요","생긴 셈이에요","생길 셈이에요","생겼는 셈이에요"],"correct":"생기는 셈이에요"},
    {"lessonId":"T6-02","topik":6,"prompt":{"ro":"모이다 → practic se adună (-는 셈이다)","en":"모이다 → practically accumulates (-는 셈이다)"},"options":["모이는 셈이에요","모인 셈이에요","모일 셈이에요","모였는 셈이에요"],"correct":"모이는 셈이에요"},
    {"lessonId":"T6-03","topik":6,"prompt":{"ro":"나빠지다 → se poate înrăutăți (prezent potential -ㄹ 수 있다)","en":"나빠지다 → can deteriorate (potential present -ㄹ 수 있다)"},"options":["나빠질 수 있어요","나빠지을 수 있어요","나빠지는 수 있어요","나빠진 수 있어요"],"correct":"나빠질 수 있어요"},
    {"lessonId":"T6-03","topik":6,"prompt":{"ro":"얻다 → poate fi obținut (prezent potential -을 수 있다)","en":"얻다 → can be obtained (potential present -을 수 있다)"},"options":["얻을 수 있어요","얻는 수 있어요","얻은 수 있어요","얻어 수 있어요"],"correct":"얻을 수 있어요"},
    {"lessonId":"T6-04","topik":6,"prompt":{"ro":"의견 + -에 불과하다 → nu este decât opinia (prezent formal -ㅂ니다)","en":"의견 + -에 불과하다 → nothing but opinion (formal present -ㅂ니다)"},"options":["불과합니다","불과입니다","불과하습니다","불과였습니다"],"correct":"불과합니다"},
    {"lessonId":"T6-04","topik":6,"prompt":{"ro":"핑계 + -에 불과하다 → nu era decât o scuză (trecut politicos)","en":"핑계 + -에 불과하다 → was nothing but an excuse (past polite)"},"options":["불과했어요","불과했습니다","불과이었어요","불과에요"],"correct":"불과했어요"},
    {"lessonId":"T6-05","topik":6,"prompt":{"ro":"쓰러지다 → aproape pe punctul de a leșina (-(으)ㄹ 지경이다)","en":"쓰러지다 → almost at the point of fainting (-(으)ㄹ 지경이다)"},"options":["쓰러질 지경이에요","쓰러지는 지경이에요","쓰러진 지경이에요","쓰러졌는 지경이에요"],"correct":"쓰러질 지경이에요"},
    {"lessonId":"T6-05","topik":6,"prompt":{"ro":"울다 → aproape pe punctul de a plânge (-(으)ㄹ 지경이다, tulpină ㄹ)","en":"울다 → almost at the point of crying (-(으)ㄹ 지경이다, ㄹ stem)"},"options":["울 지경이에요","울를 지경이에요","우는 지경이에요","울은 지경이에요"],"correct":"울 지경이에요"},
    {"lessonId":"T6-06","topik":6,"prompt":{"ro":"웃다 → ca urmare a râsului (-(으)ㄴ 나머지, aspect completat)","en":"웃다 → as a result of laughing (-(으)ㄴ 나머지, completed)"},"options":["웃은 나머지","웃는 나머지","웃을 나머지","웃었는 나머지"],"correct":"웃은 나머지"},
    {"lessonId":"T6-06","topik":6,"prompt":{"ro":"걱정하다 → ca urmare a îngrijorării (-(으)ㄴ 나머지)","en":"걱정하다 → as a result of worrying (-(으)ㄴ 나머지)"},"options":["걱정한 나머지","걱정하는 나머지","걱정했는 나머지","걱정할 나머지"],"correct":"걱정한 나머지"},
    {"lessonId":"T6-07","topik":6,"prompt":{"ro":"감사하다 → tot ce pot face este să fiu recunoscător (-(으)ㄹ 따름이다)","en":"감사하다 → all I can do is be grateful (-(으)ㄹ 따름이다)"},"options":["감사할 따름이에요","감사하는 따름이에요","감사한 따름이에요","감사했을 따름이에요"],"correct":"감사할 따름이에요"},
    {"lessonId":"T6-07","topik":6,"prompt":{"ro":"나아가다 → tot ce pot face este să merg înainte (-(으)ㄹ 따름이다)","en":"나아가다 → all I can do is move forward (-(으)ㄹ 따름이다)"},"options":["나아갈 따름입니다","나아가는 따름입니다","나아간 따름입니다","나아갔을 따름입니다"],"correct":"나아갈 따름입니다"},
    {"lessonId":"T6-08","topik":6,"prompt":{"ro":"늘다 → e firesc să crească (-기 마련이다, tulpină ㄹ)","en":"늘다 → it's natural to improve (-기 마련이다, ㄹ stem)"},"options":["늘기 마련이에요","늘르기 마련이에요","늘는기 마련이에요","늘었기 마련이에요"],"correct":"늘기 마련이에요"},
    {"lessonId":"T6-08","topik":6,"prompt":{"ro":"있다 → e firesc să existe (-기 마련이다)","en":"있다 → it's natural to exist (-기 마련이다)"},"options":["있기 마련이에요","있는기 마련이에요","있을기 마련이에요","이기 마련이에요"],"correct":"있기 마련이에요"},
]

new_puzzle = [
    {"lessonId":"T6-01","topik":6,"tiles":["재미있더라고요","정말","한국어를","보니","공부하다"],"correct":["한국어를","공부하다","보니","정말","재미있더라고요"],"hint":{"ro":"Pe măsură ce studiam coreana, mi-am dat seama că e interesantă.","en":"As I kept studying Korean, I found it was really interesting."}},
    {"lessonId":"T6-01","topik":6,"tiles":["감동적이더라고요","영화","그","정말"],"correct":["그","영화","정말","감동적이더라고요"],"hint":{"ro":"Am descoperit că filmul acela e cu adevărat emoționant.","en":"That movie turned out to be really touching."}},
    {"lessonId":"T6-02","topik":6,"tiles":["두 언어를","알면","기회가","두 배로","생기는","셈이에요"],"correct":["두 언어를","알면","기회가","두 배로","생기는","셈이에요"],"hint":{"ro":"Dacă știi două limbi, practic ți se dublează oportunitățile.","en":"If you know two languages, it practically means your opportunities double."}},
    {"lessonId":"T6-02","topik":6,"tiles":["모이는","저축하면","셈이에요","매일","조금씩","1년 후엔","꽤"],"correct":["매일","조금씩","저축하면","1년 후엔","꽤","모이는","셈이에요"],"hint":{"ro":"Dacă economisești câte puțin în fiecare zi, după un an se adună destul.","en":"If you save a little every day, after a year it adds up to quite a lot."}},
    {"lessonId":"T6-03","topik":6,"tiles":["있어요","건강이","스트레스로","나빠질","인해","수"],"correct":["스트레스로","인해","건강이","나빠질","수","있어요"],"hint":{"ro":"Din cauza stresului, sănătatea se poate înrăutăți.","en":"Due to stress, health can deteriorate."}},
    {"lessonId":"T6-03","topik":6,"tiles":["쉽게","발달로","인터넷의","수","있게","됐어요","정보를","얻을","인해"],"correct":["인터넷의","발달로","인해","정보를","쉽게","얻을","수","있게","됐어요"],"hint":{"ro":"Datorită dezvoltării internetului, a devenit posibil să obținem informații ușor.","en":"Due to the development of the internet, it became easy to obtain information."}},
    {"lessonId":"T6-04","topik":6,"tiles":["불과합니다","제","이것은","의견에"],"correct":["이것은","제","의견에","불과합니다"],"hint":{"ro":"Aceasta nu este altceva decât opinia mea.","en":"This is nothing more than my opinion."}},
    {"lessonId":"T6-04","topik":6,"tiles":["불과했어요","이유는","그","핑계에"],"correct":["그","이유는","핑계에","불과했어요"],"hint":{"ro":"Acel motiv nu era altceva decât o scuză.","en":"That reason was nothing more than an excuse."}},
    {"lessonId":"T6-05","topik":6,"tiles":["쓰러질","너무","고파서","지경이에요","배가"],"correct":["너무","배가","고파서","쓰러질","지경이에요"],"hint":{"ro":"Mi-e atât de foame că aproape leșin.","en":"I'm so hungry I'm almost about to faint."}},
    {"lessonId":"T6-05","topik":6,"tiles":["지경이에요","울","스트레스로","시험"],"correct":["시험","스트레스로","울","지경이에요"],"hint":{"ro":"Din cauza stresului de la examene, sunt pe punctul de a plânge.","en":"Due to exam stress, I'm almost at the point of crying."}},
    {"lessonId":"T6-06","topik":6,"tiles":["아팠어요","나머지","배가","너무","웃은"],"correct":["너무","웃은","나머지","배가","아팠어요"],"hint":{"ro":"Ca urmare a râsului excesiv, m-a durut burta.","en":"As a result of laughing too much, my stomach hurt."}},
    {"lessonId":"T6-06","topik":6,"tiles":["잠을","못","걱정한","나머지","잤어요","밤새"],"correct":["걱정한","나머지","밤새","잠을","못","잤어요"],"hint":{"ro":"Ca urmare a îngrijorării excesive, nu am putut dormi toată noaptea.","en":"As a result of worrying too much, I couldn't sleep all night."}},
    {"lessonId":"T6-07","topik":6,"tiles":["따름이에요","그저","감사할"],"correct":["그저","감사할","따름이에요"],"hint":{"ro":"Tot ce pot face este să fiu recunoscător/recunoscătoare.","en":"All I can do is be grateful."}},
    {"lessonId":"T6-07","topik":6,"tiles":["따름입니다","앞으로","묵묵히","나아갈"],"correct":["묵묵히","앞으로","나아갈","따름입니다"],"hint":{"ro":"Tot ce pot face este să merg înainte în tăcere.","en":"All I can do is silently move forward."}},
    {"lessonId":"T6-08","topik":6,"tiles":["늘기","연습하면","마련이에요","실력이"],"correct":["연습하면","실력이","늘기","마련이에요"],"hint":{"ro":"E firesc ca dacă exersezi, nivelul să crească.","en":"It's natural that if you practice, your skills will improve."}},
    {"lessonId":"T6-08","topik":6,"tiles":["있기","뒤에는","마련이에요","힘든","좋은","일도","일"],"correct":["좋은","일","뒤에는","힘든","일도","있기","마련이에요"],"hint":{"ro":"E firesc că după lucruri bune, să urmeze și lucruri grele.","en":"It's natural that after good things, difficult things also follow."}},
]

new_chain = [
    {"lessonId":"T6-01","topik":6,"tiles":["한국어를 공부하다 보니 정말 재미있더라고요.","처음에는 어려웠어요.","지금은 한국어가 정말 좋아요.","어떻게 공부를 시작했어요?"],"correct":["어떻게 공부를 시작했어요?","처음에는 어려웠어요.","한국어를 공부하다 보니 정말 재미있더라고요.","지금은 한국어가 정말 좋아요."],"context":{"ro":"Descoperind farmecul coreanei","en":"Discovering the charm of Korean"}},
    {"lessonId":"T6-01","topik":6,"tiles":["그 영화 정말 감동적이더라고요.","보고 나서 한참 생각했어요.","친구가 추천해 줬어요.","꼭 다시 보고 싶어요."],"correct":["친구가 추천해 줬어요.","그 영화 정말 감동적이더라고요.","보고 나서 한참 생각했어요.","꼭 다시 보고 싶어요."],"context":{"ro":"Un film emoționant","en":"A touching movie"}},
    {"lessonId":"T6-02","topik":6,"tiles":["두 언어를 알면 기회가 두 배로 생기는 셈이에요.","그래서 외국어를 배우는 게 중요해요.","언어를 하나만 아는 게 아쉬워요.","저도 영어와 한국어를 열심히 공부해요."],"correct":["언어를 하나만 아는 게 아쉬워요.","두 언어를 알면 기회가 두 배로 생기는 셈이에요.","그래서 외국어를 배우는 게 중요해요.","저도 영어와 한국어를 열심히 공부해요."],"context":{"ro":"Avantajele bilingvismului","en":"The advantages of bilingualism"}},
    {"lessonId":"T6-02","topik":6,"tiles":["매일 조금씩 저축하면 1년 후엔 꽤 모이는 셈이에요.","처음에는 조금이라도 저축하기로 했어요.","이제 꽤 큰 금액이 모였어요.","작은 것도 꾸준히 하는 게 중요해요."],"correct":["처음에는 조금이라도 저축하기로 했어요.","매일 조금씩 저축하면 1년 후엔 꽤 모이는 셈이에요.","이제 꽤 큰 금액이 모였어요.","작은 것도 꾸준히 하는 게 중요해요."],"context":{"ro":"Puterea economisirii mici dar constante","en":"The power of small but consistent savings"}},
    {"lessonId":"T6-03","topik":6,"tiles":["스트레스로 인해 건강이 나빠질 수 있어요.","규칙적인 운동이 중요해요.","요즘 스트레스가 너무 많아요.","스트레스를 잘 관리해야 해요."],"correct":["요즘 스트레스가 너무 많아요.","스트레스로 인해 건강이 나빠질 수 있어요.","스트레스를 잘 관리해야 해요.","규칙적인 운동이 중요해요."],"context":{"ro":"Efectele stresului asupra sănătății","en":"The effects of stress on health"}},
    {"lessonId":"T6-03","topik":6,"tiles":["인터넷의 발달로 인해 정보를 쉽게 얻을 수 있게 됐어요.","하지만 잘못된 정보도 많아졌어요.","예전에는 도서관에 가야 했어요.","정보를 비판적으로 보는 눈이 필요해요."],"correct":["예전에는 도서관에 가야 했어요.","인터넷의 발달로 인해 정보를 쉽게 얻을 수 있게 됐어요.","하지만 잘못된 정보도 많아졌어요.","정보를 비판적으로 보는 눈이 필요해요."],"context":{"ro":"Internetul și accesul la informații","en":"The internet and access to information"}},
    {"lessonId":"T6-04","topik":6,"tiles":["이것은 제 의견에 불과합니다.","다른 분들의 생각은 어떤가요?","이 주제에 대해 이야기하고 싶었어요.","모든 의견을 존중해요."],"correct":["이 주제에 대해 이야기하고 싶었어요.","이것은 제 의견에 불과합니다.","다른 분들의 생각은 어떤가요?","모든 의견을 존중해요."],"context":{"ro":"Împărtășind o opinie","en":"Sharing an opinion"}},
    {"lessonId":"T6-04","topik":6,"tiles":["그 이유는 핑계에 불과했어요.","결국 솔직하게 말했어요.","처음에는 이유를 들었어요.","진실을 말하는 게 중요해요."],"correct":["처음에는 이유를 들었어요.","그 이유는 핑계에 불과했어요.","결국 솔직하게 말했어요.","진실을 말하는 게 중요해요."],"context":{"ro":"Scuze și adevăr","en":"Excuses and truth"}},
    {"lessonId":"T6-05","topik":6,"tiles":["너무 배가 고파서 쓰러질 지경이에요.","오늘 아무것도 못 먹었어요.","빨리 밥을 먹어야겠어요.","지금 당장 식당에 가요."],"correct":["오늘 아무것도 못 먹었어요.","너무 배가 고파서 쓰러질 지경이에요.","지금 당장 식당에 가요.","빨리 밥을 먹어야겠어요."],"context":{"ro":"Foame extremă","en":"Extreme hunger"}},
    {"lessonId":"T6-05","topik":6,"tiles":["시험 스트레스로 울 지경이에요.","모두 열심히 응원해요.","시험이 너무 어려웠어요.","다음에는 더 잘 준비할 거예요."],"correct":["시험이 너무 어려웠어요.","시험 스트레스로 울 지경이에요.","다음에는 더 잘 준비할 거예요.","모두 열심히 응원해요."],"context":{"ro":"Stresul examenelor","en":"Exam stress"}},
    {"lessonId":"T6-06","topik":6,"tiles":["너무 웃은 나머지 배가 아팠어요.","그 이후로는 웃음을 참았어요.","정말 재미있는 이야기를 들었어요.","눈물이 날 만큼 웃었어요."],"correct":["정말 재미있는 이야기를 들었어요.","너무 웃은 나머지 배가 아팠어요.","눈물이 날 만큼 웃었어요.","그 이후로는 웃음을 참았어요."],"context":{"ro":"Râs nestăpânit","en":"Uncontrollable laughter"}},
    {"lessonId":"T6-06","topik":6,"tiles":["걱정한 나머지 밤새 잠을 못 잤어요.","아침에 일어나니 피곤했어요.","중요한 발표가 있었어요.","결국 발표는 잘 끝났어요."],"correct":["중요한 발표가 있었어요.","걱정한 나머지 밤새 잠을 못 잤어요.","아침에 일어나니 피곤했어요.","결국 발표는 잘 끝났어요."],"context":{"ro":"O noapte de îngrijorare","en":"A night of worry"}},
    {"lessonId":"T6-07","topik":6,"tiles":["그저 감사할 따름이에요.","덕분에 많이 성장했어요.","정말 좋은 선생님을 만났어요.","앞으로도 잘 부탁드립니다."],"correct":["정말 좋은 선생님을 만났어요.","덕분에 많이 성장했어요.","그저 감사할 따름이에요.","앞으로도 잘 부탁드립니다."],"context":{"ro":"Recunoștință față de un profesor","en":"Gratitude toward a teacher"}},
    {"lessonId":"T6-07","topik":6,"tiles":["묵묵히 앞으로 나아갈 따름입니다.","포기하지 않겠습니다.","힘든 상황이 계속되고 있어요.","결국 좋은 결과가 있을 거예요."],"correct":["힘든 상황이 계속되고 있어요.","포기하지 않겠습니다.","묵묵히 앞으로 나아갈 따름입니다.","결국 좋은 결과가 있을 거예요."],"context":{"ro":"Perseverând prin dificultăți","en":"Persevering through difficulties"}},
    {"lessonId":"T6-08","topik":6,"tiles":["연습하면 실력이 늘기 마련이에요.","처음에는 잘 못 해도 괜찮아요.","꾸준히 연습하는 것이 중요해요.","지금은 많이 실력이 좋아졌어요."],"correct":["처음에는 잘 못 해도 괜찮아요.","꾸준히 연습하는 것이 중요해요.","연습하면 실력이 늘기 마련이에요.","지금은 많이 실력이 좋아졌어요."],"context":{"ro":"Practica face progres","en":"Practice makes progress"}},
    {"lessonId":"T6-08","topik":6,"tiles":["좋은 일 뒤에는 힘든 일도 있기 마련이에요.","그래서 좋을 때 미리 준비해야 해요.","요즘 정말 행복해요.","힘든 일이 와도 잘 이겨낼 거예요."],"correct":["요즘 정말 행복해요.","좋은 일 뒤에는 힘든 일도 있기 마련이에요.","그래서 좋을 때 미리 준비해야 해요.","힘든 일이 와도 잘 이겨낼 거예요."],"context":{"ro":"Viața are suișuri și coborâșuri","en":"Life has ups and downs"}},
]

data['ko-ro'].extend(new_ko_ro)
data['ro-ko'].extend(new_ro_ko)
data['particle'].extend(new_particle)
data['particlePlus'].extend(new_particle_plus)
data['conjug'].extend(new_conjug)
data['puzzle'].extend(new_puzzle)
data['chain'].extend(new_chain)

with open('data/exercises.json', 'w', encoding='utf-8') as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

print("Done! New counts:")
print({k: len(v) for k, v in data.items()})
