import json

with open('data/exercises.json', 'r', encoding='utf-8') as f:
    data = json.load(f)

new_ko_ro = [
    {"lessonId":"T4-01","topik":4,"q":"오늘 비가 올 것 같아요.","answers":{"ro":["Se pare că azi va ploua.","Azi plouă mult.","Azi nu plouă deloc.","Mi se pare că ieri a plouat."],"en":["It seems like it will rain today.","It's raining today.","It doesn't seem like rain.","It rained a lot yesterday."]},"correct":{"ro":"Se pare că azi va ploua.","en":"It seems like it will rain today."}},
    {"lessonId":"T4-01","topik":4,"q":"그 사람이 화가 난 것 같아요.","answers":{"ro":["Se pare că acea persoană e supărată.","Acea persoană e fericită.","Acea persoană nu e supărată.","Se pare că acea persoană doarme."],"en":["It seems like that person is angry.","That person seems happy.","That person is not angry.","It seems like that person is sleeping."]},"correct":{"ro":"Se pare că acea persoană e supărată.","en":"It seems like that person is angry."}},
    {"lessonId":"T4-02","topik":4,"q":"건강해지도록 매일 운동해요.","answers":{"ro":["Fac sport în fiecare zi ca să mă fac sănătos/sănătoasă.","Fac sport uneori pentru distracție.","Nu fac sport deloc.","Merg la doctor în fiecare zi."],"en":["I exercise every day so that I become healthy.","I sometimes exercise for fun.","I don't exercise at all.","I go to the doctor every day."]},"correct":{"ro":"Fac sport în fiecare zi ca să mă fac sănătos/sănătoasă.","en":"I exercise every day so that I become healthy."}},
    {"lessonId":"T4-02","topik":4,"q":"시험에 합격하도록 열심히 공부해요.","answers":{"ro":["Studiez din greu ca să promovez examenul.","Studiez uneori pentru distracție.","Nu studiez deloc.","Studiez ca să mă relaxez."],"en":["I study hard so that I pass the exam.","I sometimes study for fun.","I don't study at all.","I study to relax."]},"correct":{"ro":"Studiez din greu ca să promovez examenul.","en":"I study hard so that I pass the exam."}},
    {"lessonId":"T4-03","topik":4,"q":"알수록 더 어려워요.","answers":{"ro":["Cu cât știi mai multe, cu atât devine mai greu.","Cu cât studiezi mai mult, cu atât este mai ușor.","Nu este deloc greu.","Totul devine mai ușor în timp."],"en":["The more you know, the harder it gets.","The more you study, the easier it gets.","It's not difficult at all.","Everything gets easier over time."]},"correct":{"ro":"Cu cât știi mai multe, cu atât devine mai greu.","en":"The more you know, the harder it gets."}},
    {"lessonId":"T4-03","topik":4,"q":"한국어는 연습할수록 실력이 늘어요.","answers":{"ro":["Cu cât exersezi mai mult coreana, cu atât nivelul crește.","Coreana este prea grea de exersat.","Exersatul nu ajută la coreeană.","Cu cât exersezi, cu atât uiți mai repede."],"en":["The more you practice Korean, the better you get.","Korean is too hard to practice.","Practicing doesn't help with Korean.","The more you practice, the faster you forget."]},"correct":{"ro":"Cu cât exersezi mai mult coreana, cu atât nivelul crește.","en":"The more you practice Korean, the better you get."}},
    {"lessonId":"T4-04","topik":4,"q":"사람에 따라 의견이 달라요.","answers":{"ro":["Opiniile diferă în funcție de persoană.","Toată lumea are aceeași opinie.","Opinia nu contează.","Persoanele nu au opinii."],"en":["Opinions differ depending on the person.","Everyone has the same opinion.","Opinions don't matter.","People don't have opinions."]},"correct":{"ro":"Opiniile diferă în funcție de persoană.","en":"Opinions differ depending on the person."}},
    {"lessonId":"T4-04","topik":4,"q":"연구에 따르면 수면이 중요하다고 해요.","answers":{"ro":["Conform cercetărilor, se spune că somnul este important.","Cercetările spun că somnul e neimportant.","Nu știm dacă somnul e important.","Cercetătorii nu dorm deloc."],"en":["According to research, sleep is said to be important.","Research says sleep is unimportant.","We don't know if sleep is important.","Researchers don't sleep at all."]},"correct":{"ro":"Conform cercetărilor, se spune că somnul este important.","en":"According to research, sleep is said to be important."}},
    {"lessonId":"T4-05","topik":4,"q":"먹은 데도 배가 고파요.","answers":{"ro":["Deși am mâncat, îmi este foame.","Nu mi-e foame deloc.","Am mâncat și sunt sătul/sătulă.","Nu am mâncat nimic astăzi."],"en":["Even though I ate, I'm still hungry.","I'm not hungry at all.","I ate and I'm full.","I haven't eaten anything today."]},"correct":{"ro":"Deși am mâncat, îmi este foame.","en":"Even though I ate, I'm still hungry."}},
    {"lessonId":"T4-05","topik":4,"q":"피곤한 데도 일을 계속했어요.","answers":{"ro":["Deși eram obosit/obosită, am continuat să lucrez.","M-am odihnit pentru că eram obosit/obosită.","Nu eram deloc obosit/obosită.","Am terminat munca devreme."],"en":["Even though I was tired, I continued working.","I rested because I was tired.","I wasn't tired at all.","I finished work early."]},"correct":{"ro":"Deși eram obosit/obosită, am continuat să lucrez.","en":"Even though I was tired, I continued working."}},
    {"lessonId":"T4-06","topik":4,"q":"혼자 살다 보니 요리를 배우게 됐어요.","answers":{"ro":["Trăind singur/singură, am ajuns să învăț să gătesc.","Am mers la un curs de gătit.","Nu știu să gătesc deloc.","Locuiesc cu familia mea."],"en":["As I kept living alone, I ended up learning to cook.","I went to a cooking class.","I can't cook at all.","I live with my family."]},"correct":{"ro":"Trăind singur/singură, am ajuns să învăț să gătesc.","en":"As I kept living alone, I ended up learning to cook."}},
    {"lessonId":"T4-06","topik":4,"q":"여행을 많이 하다 보니 새로운 문화를 알게 됐어요.","answers":{"ro":["Călătorind mult, am ajuns să cunosc culturi noi.","Nu am călătorit niciodată.","Călătoriile nu m-au învățat nimic.","Am citit despre culturile din lume."],"en":["As I kept traveling a lot, I got to know new cultures.","I've never traveled.","Traveling hasn't taught me anything.","I read about world cultures."]},"correct":{"ro":"Călătorind mult, am ajuns să cunosc culturi noi.","en":"As I kept traveling a lot, I got to know new cultures."}},
    {"lessonId":"T4-07","topik":4,"q":"건강한 한 일을 계속할 거예요.","answers":{"ro":["Cât timp sunt sănătos/sănătoasă, voi continua să lucrez.","Nu mai vreau să lucrez.","Lucrez numai când sunt bolnav/bolnavă.","Am renunțat la muncă."],"en":["As long as I'm healthy, I'll continue working.","I don't want to work anymore.","I only work when I'm sick.","I've quit working."]},"correct":{"ro":"Cât timp sunt sănătos/sănătoasă, voi continua să lucrez.","en":"As long as I'm healthy, I'll continue working."}},
    {"lessonId":"T4-07","topik":4,"q":"규칙을 지키는 한 문제없어요.","answers":{"ro":["Cât timp respecți regulile, nu e nicio problemă.","Regulile sunt prea stricte.","Nu există reguli.","Există mereu probleme."],"en":["As long as you follow the rules, there's no problem.","The rules are too strict.","There are no rules.","There are always problems."]},"correct":{"ro":"Cât timp respecți regulile, nu e nicio problemă.","en":"As long as you follow the rules, there's no problem."}},
    {"lessonId":"T4-08","topik":4,"q":"도시는 편리한 반면 시끄러워요.","answers":{"ro":["Orașul este convenabil, dar în schimb e zgomotos.","Orașul este liniștit și convenabil.","Orașul este zgomotos și inconvenabil.","Orașul nu e nici convenabil nici zgomotos."],"en":["The city is convenient, but on the other hand it's noisy.","The city is quiet and convenient.","The city is noisy and inconvenient.","The city is neither convenient nor noisy."]},"correct":{"ro":"Orașul este convenabil, dar în schimb e zgomotos.","en":"The city is convenient, but on the other hand it's noisy."}},
    {"lessonId":"T4-08","topik":4,"q":"여름은 더운 반면 겨울은 추워요.","answers":{"ro":["Vara este caldă, în schimb iarna este friguroasă.","Vara și iarna sunt la fel.","Vara este friguroasă și iarna este caldă.","Nu îmi place nici vara nici iarna."],"en":["Summer is hot, whereas winter is cold.","Summer and winter are the same.","Summer is cold and winter is hot.","I don't like either summer or winter."]},"correct":{"ro":"Vara este caldă, în schimb iarna este friguroasă.","en":"Summer is hot, whereas winter is cold."}},
    {"lessonId":"T4-09","topik":4,"q":"케이크를 다 먹어 버렸어요.","answers":{"ro":["Am mâncat tot tortul.","Nu am mâncat tortul.","Am lăsat jumătate din tort.","Am cumpărat un tort."],"en":["I ate all the cake.","I didn't eat the cake.","I left half the cake.","I bought a cake."]},"correct":{"ro":"Am mâncat tot tortul.","en":"I ate all the cake."}},
    {"lessonId":"T4-09","topik":4,"q":"지갑을 잃어 버렸어요.","answers":{"ro":["Mi-am pierdut portofelul.","Mi-am găsit portofelul.","Mi-am cumpărat un portofel nou.","Am uitat portofelul acasă."],"en":["I lost my wallet.","I found my wallet.","I bought a new wallet.","I left my wallet at home."]},"correct":{"ro":"Mi-am pierdut portofelul.","en":"I lost my wallet."}},
    {"lessonId":"T4-10","topik":4,"q":"밥을 먹다가 전화가 왔어요.","answers":{"ro":["În timp ce mâncam, a venit un apel telefonic.","Am terminat masa și apoi am primit un apel.","Am sunat pe cineva în timp ce mâncam.","Am mâncat după ce am vorbit la telefon."],"en":["While eating, a phone call came.","I finished eating and then got a call.","I called someone while eating.","I ate after talking on the phone."]},"correct":{"ro":"În timp ce mâncam, a venit un apel telefonic.","en":"While eating, a phone call came."}},
    {"lessonId":"T4-10","topik":4,"q":"음악을 듣다가 잠이 들었어요.","answers":{"ro":["În timp ce ascultam muzică, am adormit.","M-am trezit din muzică.","Am oprit muzica și am adormit.","Am ascultat muzică toată noaptea."],"en":["While listening to music, I fell asleep.","I woke up from the music.","I turned off the music and fell asleep.","I listened to music all night."]},"correct":{"ro":"În timp ce ascultam muzică, am adormit.","en":"While listening to music, I fell asleep."}},
    {"lessonId":"T4-11","topik":4,"q":"시험이 없었으면 좋겠어요.","answers":{"ro":["Mi-ar plăcea să nu fie examene.","Îmi plac examenele.","Examenele sunt ușoare.","Abia aștept examenul."],"en":["I wish there were no exams.","I love exams.","Exams are easy.","I can't wait for the exam."]},"correct":{"ro":"Mi-ar plăcea să nu fie examene.","en":"I wish there were no exams."}},
    {"lessonId":"T4-11","topik":4,"q":"방학이 더 길었으면 좋겠어요.","answers":{"ro":["Mi-ar plăcea ca vacanța să fie mai lungă.","Vacanța este prea lungă.","Nu îmi place vacanța.","Abia aștept să mă întorc la școală."],"en":["I wish the vacation were longer.","The vacation is too long.","I don't like vacation.","I can't wait to go back to school."]},"correct":{"ro":"Mi-ar plăcea ca vacanța să fie mai lungă.","en":"I wish the vacation were longer."}},
]

new_ro_ko = [
    {"lessonId":"T4-01","topik":4,"prompt":{"ro":"Se pare că azi va ploua.","en":"It seems like it will rain today."},"options":["오늘 비가 올 것 같아요.","오늘 날씨가 좋아요.","오늘 비가 많이 왔어요.","오늘 눈이 올 것 같아요."],"correct":"오늘 비가 올 것 같아요."},
    {"lessonId":"T4-01","topik":4,"prompt":{"ro":"Se pare că acea persoană e supărată.","en":"It seems like that person is angry."},"options":["그 사람이 화가 난 것 같아요.","그 사람이 기분이 좋은 것 같아요.","그 사람이 자는 것 같아요.","그 사람이 화가 났어요."],"correct":"그 사람이 화가 난 것 같아요."},
    {"lessonId":"T4-02","topik":4,"prompt":{"ro":"Fac sport în fiecare zi ca să mă fac sănătos/sănătoasă.","en":"I exercise every day so that I become healthy."},"options":["건강해지도록 매일 운동해요.","건강하기 때문에 운동해요.","운동하면 건강해져요.","매일 운동하고 싶어요."],"correct":"건강해지도록 매일 운동해요."},
    {"lessonId":"T4-02","topik":4,"prompt":{"ro":"Studiez din greu ca să promovez examenul.","en":"I study hard so that I pass the exam."},"options":["시험에 합격하도록 열심히 공부해요.","시험에 합격해서 공부해요.","열심히 공부하면 합격할 거예요.","시험 공부를 열심히 했어요."],"correct":"시험에 합격하도록 열심히 공부해요."},
    {"lessonId":"T4-03","topik":4,"prompt":{"ro":"Cu cât știi mai multe, cu atât devine mai greu.","en":"The more you know, the harder it gets."},"options":["알수록 더 어려워요.","알면 알수록 쉬워요.","더 알고 싶어요.","모를수록 더 어려워요."],"correct":"알수록 더 어려워요."},
    {"lessonId":"T4-03","topik":4,"prompt":{"ro":"Cu cât exersezi mai mult coreana, cu atât nivelul crește.","en":"The more you practice Korean, the better you get."},"options":["한국어는 연습할수록 실력이 늘어요.","한국어는 어려워서 실력이 안 늘어요.","한국어를 연습하면 재미있어요.","한국어 실력이 늘었으면 좋겠어요."],"correct":"한국어는 연습할수록 실력이 늘어요."},
    {"lessonId":"T4-04","topik":4,"prompt":{"ro":"Opiniile diferă în funcție de persoană.","en":"Opinions differ depending on the person."},"options":["사람에 따라 의견이 달라요.","사람마다 같은 의견이에요.","의견이 항상 달라요.","사람들은 의견이 없어요."],"correct":"사람에 따라 의견이 달라요."},
    {"lessonId":"T4-04","topik":4,"prompt":{"ro":"Conform cercetărilor, se spune că somnul este important.","en":"According to research, sleep is said to be important."},"options":["연구에 따르면 수면이 중요하다고 해요.","수면이 중요하지 않다고 해요.","연구에 따르면 운동이 중요해요.","수면은 건강에 좋아요."],"correct":"연구에 따르면 수면이 중요하다고 해요."},
    {"lessonId":"T4-05","topik":4,"prompt":{"ro":"Deși am mâncat, îmi este foame.","en":"Even though I ate, I'm still hungry."},"options":["먹은 데도 배가 고파요.","먹어서 배가 불러요.","안 먹어서 배가 고파요.","배가 고프지 않아요."],"correct":"먹은 데도 배가 고파요."},
    {"lessonId":"T4-05","topik":4,"prompt":{"ro":"Deși eram obosit/obosită, am continuat să lucrez.","en":"Even though I was tired, I continued working."},"options":["피곤한 데도 일을 계속했어요.","피곤해서 일을 그만했어요.","피곤하지 않았어요.","일이 끝나서 쉬었어요."],"correct":"피곤한 데도 일을 계속했어요."},
    {"lessonId":"T4-06","topik":4,"prompt":{"ro":"Trăind singur/singură, am ajuns să învăț să gătesc.","en":"As I kept living alone, I ended up learning to cook."},"options":["혼자 살다 보니 요리를 배우게 됐어요.","요리 학원에 다니게 됐어요.","혼자 살기 때문에 요리해요.","요리를 못 배웠어요."],"correct":"혼자 살다 보니 요리를 배우게 됐어요."},
    {"lessonId":"T4-06","topik":4,"prompt":{"ro":"Călătorind mult, am ajuns să cunosc culturi noi.","en":"As I kept traveling a lot, I got to know new cultures."},"options":["여행을 많이 하다 보니 새로운 문화를 알게 됐어요.","여행을 해서 피곤해졌어요.","새로운 문화를 책에서 배웠어요.","여행을 많이 하고 싶어요."],"correct":"여행을 많이 하다 보니 새로운 문화를 알게 됐어요."},
    {"lessonId":"T4-07","topik":4,"prompt":{"ro":"Cât timp sunt sănătos/sănătoasă, voi continua să lucrez.","en":"As long as I'm healthy, I'll continue working."},"options":["건강한 한 일을 계속할 거예요.","건강해서 일을 그만뒀어요.","일을 계속하면 건강해져요.","건강이 안 좋으면 쉴 거예요."],"correct":"건강한 한 일을 계속할 거예요."},
    {"lessonId":"T4-07","topik":4,"prompt":{"ro":"Cât timp respecți regulile, nu e nicio problemă.","en":"As long as you follow the rules, there's no problem."},"options":["규칙을 지키는 한 문제없어요.","규칙이 없으면 문제없어요.","규칙을 안 지키면 괜찮아요.","항상 문제가 있어요."],"correct":"규칙을 지키는 한 문제없어요."},
    {"lessonId":"T4-08","topik":4,"prompt":{"ro":"Orașul este convenabil, dar în schimb e zgomotos.","en":"The city is convenient, but on the other hand it's noisy."},"options":["도시는 편리한 반면 시끄러워요.","도시는 편리하고 조용해요.","도시는 시끄럽고 불편해요.","도시는 조용한 반면 불편해요."],"correct":"도시는 편리한 반면 시끄러워요."},
    {"lessonId":"T4-08","topik":4,"prompt":{"ro":"Vara este caldă, în schimb iarna este friguroasă.","en":"Summer is hot, whereas winter is cold."},"options":["여름은 더운 반면 겨울은 추워요.","여름은 춥고 겨울은 더워요.","여름과 겨울은 똑같아요.","여름은 더운 편이에요."],"correct":"여름은 더운 반면 겨울은 추워요."},
    {"lessonId":"T4-09","topik":4,"prompt":{"ro":"Am mâncat tot tortul.","en":"I ate all the cake."},"options":["케이크를 다 먹어 버렸어요.","케이크를 사 버렸어요.","케이크를 반만 먹었어요.","케이크를 안 먹었어요."],"correct":"케이크를 다 먹어 버렸어요."},
    {"lessonId":"T4-09","topik":4,"prompt":{"ro":"Mi-am pierdut portofelul.","en":"I lost my wallet."},"options":["지갑을 잃어 버렸어요.","지갑을 찾아 버렸어요.","지갑을 샀어요.","지갑을 집에 두고 왔어요."],"correct":"지갑을 잃어 버렸어요."},
    {"lessonId":"T4-10","topik":4,"prompt":{"ro":"În timp ce mâncam, a venit un apel telefonic.","en":"While eating, a phone call came."},"options":["밥을 먹다가 전화가 왔어요.","전화를 받고 나서 밥을 먹었어요.","밥을 먹으면서 전화했어요.","전화가 와서 밥을 못 먹었어요."],"correct":"밥을 먹다가 전화가 왔어요."},
    {"lessonId":"T4-10","topik":4,"prompt":{"ro":"În timp ce ascultam muzică, am adormit.","en":"While listening to music, I fell asleep."},"options":["음악을 듣다가 잠이 들었어요.","잠을 자다가 음악을 들었어요.","음악 때문에 잠이 안 왔어요.","음악을 들으면서 공부했어요."],"correct":"음악을 듣다가 잠이 들었어요."},
    {"lessonId":"T4-11","topik":4,"prompt":{"ro":"Mi-ar plăcea să nu fie examene.","en":"I wish there were no exams."},"options":["시험이 없었으면 좋겠어요.","시험이 있어서 좋아요.","시험이 쉬웠으면 좋겠어요.","시험 공부를 더 했으면 좋겠어요."],"correct":"시험이 없었으면 좋겠어요."},
    {"lessonId":"T4-11","topik":4,"prompt":{"ro":"Mi-ar plăcea ca vacanța să fie mai lungă.","en":"I wish the vacation were longer."},"options":["방학이 더 길었으면 좋겠어요.","방학이 끝났으면 좋겠어요.","방학이 짧았으면 좋겠어요.","방학이 좋아요."],"correct":"방학이 더 길었으면 좋겠어요."},
]

new_particle = [
    {"lessonId":"T4-01","topik":4,"template":"오늘 비___ 올 것 같아요.","options":["가","를","은","도"],"correct":"가","hint":{"ro":"Subiect: 비 (ploaie) — se termină în vocală → 가","en":"Subject: 비 (rain) — ends in vowel → 가"}},
    {"lessonId":"T4-01","topik":4,"template":"그 사람___ 화가 난 것 같아요.","options":["이","가","은","를"],"correct":"이","hint":{"ro":"Subiect: 사람 (persoană) — se termină în consoană → 이","en":"Subject: 사람 (person) — ends in consonant → 이"}},
    {"lessonId":"T4-02","topik":4,"template":"건강해지도록 매일 운동___ 해요.","options":["을","이","는","에"],"correct":"을","hint":{"ro":"Complement direct: 운동 — se termină în consoană → 을","en":"Object: 운동 — ends in consonant → 을"}},
    {"lessonId":"T4-02","topik":4,"template":"시험___ 합격하도록 열심히 공부해요.","options":["에","을","이","도"],"correct":"에","hint":{"ro":"시험에 합격하다 = a promova examenul (particulă fixă 에)","en":"시험에 합격하다 = to pass the exam (fixed particle 에)"}},
    {"lessonId":"T4-03","topik":4,"template":"한국어___ 알수록 더 어려워요.","options":["를","은","이","에"],"correct":"를","hint":{"ro":"Complement direct: 한국어 — se termină în vocală → 를","en":"Object: 한국어 — ends in vowel → 를"}},
    {"lessonId":"T4-03","topik":4,"template":"한국어는 연습할수록 실력___ 늘어요.","options":["이","가","을","도"],"correct":"이","hint":{"ro":"Subiect: 실력 — se termină în consoană → 이","en":"Subject: 실력 — ends in consonant → 이"}},
    {"lessonId":"T4-04","topik":4,"template":"사람에 따라 의견___ 달라요.","options":["이","가","을","는"],"correct":"이","hint":{"ro":"Subiect: 의견 — se termină în consoană → 이","en":"Subject: 의견 — ends in consonant → 이"}},
    {"lessonId":"T4-04","topik":4,"template":"연구___ 따르면 수면이 중요하다고 해요.","options":["에","를","이","도"],"correct":"에","hint":{"ro":"연구에 따르면 = conform cercetărilor (particulă fixă 에)","en":"연구에 따르면 = according to research (fixed particle 에)"}},
    {"lessonId":"T4-05","topik":4,"template":"먹은 데도 배___ 고파요.","options":["가","는","이","를"],"correct":"가","hint":{"ro":"Subiect: 배 (burtă) — se termină în vocală → 가","en":"Subject: 배 (stomach) — ends in vowel → 가"}},
    {"lessonId":"T4-05","topik":4,"template":"피곤한 데도 일___ 계속했어요.","options":["을","이","는","에"],"correct":"을","hint":{"ro":"Complement direct: 일 — se termină în consoană → 을","en":"Object: 일 — ends in consonant → 을"}},
    {"lessonId":"T4-06","topik":4,"template":"혼자 살다 보니 요리___ 배우게 됐어요.","options":["를","이","은","도"],"correct":"를","hint":{"ro":"Complement direct: 요리 — se termină în vocală → 를","en":"Object: 요리 — ends in vowel → 를"}},
    {"lessonId":"T4-06","topik":4,"template":"여행___ 많이 하다 보니 새로운 문화를 알게 됐어요.","options":["을","가","는","도"],"correct":"을","hint":{"ro":"Complement direct: 여행 — se termină în consoană → 을","en":"Object: 여행 — ends in consonant → 을"}},
    {"lessonId":"T4-07","topik":4,"template":"건강한 한 일___ 계속할 거예요.","options":["을","이","는","에"],"correct":"을","hint":{"ro":"Complement direct: 일 — se termină în consoană → 을","en":"Object: 일 — ends in consonant → 을"}},
    {"lessonId":"T4-07","topik":4,"template":"규칙___ 지키는 한 문제없어요.","options":["을","이","는","에"],"correct":"을","hint":{"ro":"Complement direct: 규칙 — se termină în consoană → 을","en":"Object: 규칙 — ends in consonant → 을"}},
    {"lessonId":"T4-08","topik":4,"template":"도시___ 편리한 반면 시끄러워요.","options":["는","가","을","에"],"correct":"는","hint":{"ro":"Topic: 도시 — se termină în vocală → 는","en":"Topic: 도시 — ends in vowel → 는"}},
    {"lessonId":"T4-08","topik":4,"template":"여름___ 더운 반면 겨울은 추워요.","options":["은","이","를","도"],"correct":"은","hint":{"ro":"Topic: 여름 — se termină în consoană → 은","en":"Topic: 여름 — ends in consonant → 은"}},
    {"lessonId":"T4-09","topik":4,"template":"케이크___ 다 먹어 버렸어요.","options":["를","가","은","에"],"correct":"를","hint":{"ro":"Complement direct: 케이크 — se termină în vocală → 를","en":"Object: 케이크 — ends in vowel → 를"}},
    {"lessonId":"T4-09","topik":4,"template":"지갑___ 잃어 버렸어요.","options":["을","가","는","에"],"correct":"을","hint":{"ro":"Complement direct: 지갑 — se termină în consoană → 을","en":"Object: 지갑 — ends in consonant → 을"}},
    {"lessonId":"T4-10","topik":4,"template":"밥을 먹다가 전화___ 왔어요.","options":["가","를","는","도"],"correct":"가","hint":{"ro":"Subiect: 전화 — se termină în vocală → 가","en":"Subject: 전화 — ends in vowel → 가"}},
    {"lessonId":"T4-10","topik":4,"template":"음악___ 듣다가 잠이 들었어요.","options":["을","이","는","에"],"correct":"을","hint":{"ro":"Complement direct: 음악 — se termină în consoană → 을","en":"Object: 음악 — ends in consonant → 을"}},
    {"lessonId":"T4-11","topik":4,"template":"시험___ 없었으면 좋겠어요.","options":["이","가","을","는"],"correct":"이","hint":{"ro":"Subiect: 시험 — se termină în consoană → 이","en":"Subject: 시험 — ends in consonant → 이"}},
    {"lessonId":"T4-11","topik":4,"template":"방학___ 더 길었으면 좋겠어요.","options":["이","가","을","도"],"correct":"이","hint":{"ro":"Subiect: 방학 — se termină în consoană → 이","en":"Subject: 방학 — ends in consonant → 이"}},
]

new_particle_plus = [
    {"lessonId":"T4-01","topik":4,"template":"오늘 비___ 많이 오고 바람___ 강할 것 같아요.","options":[["가","도"],["이","도"],["가","이"],["를","가"]],"correct":["가","도"],"hint":{"ro":"비 (vocală→가), 바람 = și (도)","en":"비 (vowel→가), 바람 = also (도)"}},
    {"lessonId":"T4-01","topik":4,"template":"친구___ 화가 났고 저___ 슬펐어요.","options":[["가","도"],["이","도"],["가","는"],["이","가"]],"correct":["가","도"],"hint":{"ro":"친구 (vocală→가), 저 = și eu (도)","en":"친구 (vowel→가), 저 = me too (도)"}},
    {"lessonId":"T4-02","topik":4,"template":"우리___ 건강해지도록 매일 운동___ 해요.","options":[["는","을"],["이","을"],["는","를"],["가","을"]],"correct":["는","을"],"hint":{"ro":"우리 (vocală→는, topic), 운동 (consoană→을, obiect)","en":"우리 (vowel→는, topic), 운동 (consonant→을, object)"}},
    {"lessonId":"T4-02","topik":4,"template":"학생들___ 시험___ 합격하도록 열심히 공부해요.","options":[["이","에"],["가","에"],["이","를"],["가","를"]],"correct":["이","에"],"hint":{"ro":"학생들 (consoană→이, subiect), 시험에 합격하다 (particulă fixă 에)","en":"학생들 (consonant→이, subject), 시험에 합격하다 (fixed particle 에)"}},
    {"lessonId":"T4-03","topik":4,"template":"한국어___ 알수록 더 어렵고 영어___ 쉬운 것 같아요.","options":[["를","는"],["은","는"],["를","이"],["이","는"]],"correct":["를","는"],"hint":{"ro":"한국어 (vocală→를, obiect), 영어 (vocală→는, topic)","en":"한국어 (vowel→를, object), 영어 (vowel→는, topic)"}},
    {"lessonId":"T4-03","topik":4,"template":"한국어___ 연습할수록 실력___ 늘어요.","options":[["는","이"],["를","이"],["는","가"],["이","이"]],"correct":["는","이"],"hint":{"ro":"한국어 (vocală→는, topic), 실력 (consoană→이, subiect)","en":"한국어 (vowel→는, topic), 실력 (consonant→이, subject)"}},
    {"lessonId":"T4-04","topik":4,"template":"사람___ 따라 의견___ 달라요.","options":[["에","이"],["에","가"],["를","이"],["이","가"]],"correct":["에","이"],"hint":{"ro":"사람에 따라 (particulă fixă 에), 의견 (consoană→이, subiect)","en":"사람에 따라 (fixed 에), 의견 (consonant→이, subject)"}},
    {"lessonId":"T4-04","topik":4,"template":"연구___ 따르면 수면___ 중요하다고 해요.","options":[["에","이"],["를","이"],["에","가"],["이","가"]],"correct":["에","이"],"hint":{"ro":"연구에 따르면 (particulă fixă 에), 수면 (consoană→이, subiect)","en":"연구에 따르면 (fixed 에), 수면 (consonant→이, subject)"}},
    {"lessonId":"T4-05","topik":4,"template":"밥___ 먹은 데도 배___ 고파요.","options":[["을","가"],["이","가"],["를","가"],["을","이"]],"correct":["을","가"],"hint":{"ro":"밥 (consoană→을, obiect), 배 (vocală→가, subiect)","en":"밥 (consonant→을, object), 배 (vowel→가, subject)"}},
    {"lessonId":"T4-05","topik":4,"template":"피곤한 데도 일___ 계속하고 공부___ 했어요.","options":[["을","도"],["이","도"],["를","도"],["을","는"]],"correct":["을","도"],"hint":{"ro":"일 (consoană→을, obiect), 공부도 = și studiul (도)","en":"일 (consonant→을, object), 공부도 = also studying (도)"}},
    {"lessonId":"T4-06","topik":4,"template":"혼자 살다 보니 요리___ 배우고 청소___ 잘하게 됐어요.","options":[["를","도"],["을","도"],["이","도"],["를","가"]],"correct":["를","도"],"hint":{"ro":"요리 (vocală→를, obiect), 청소도 = și curățenia (도)","en":"요리 (vowel→를, object), 청소도 = also cleaning (도)"}},
    {"lessonId":"T4-06","topik":4,"template":"여행___ 많이 하다 보니 새로운 문화___ 알게 됐어요.","options":[["을","를"],["이","를"],["을","이"],["가","를"]],"correct":["을","를"],"hint":{"ro":"여행 (consoană→을, obiect), 문화 (vocală→를, obiect)","en":"여행 (consonant→을, object), 문화 (vowel→를, object)"}},
    {"lessonId":"T4-07","topik":4,"template":"몸___ 건강한 한 일___ 계속할 거예요.","options":[["이","을"],["가","을"],["이","를"],["가","를"]],"correct":["이","을"],"hint":{"ro":"몸 (consoană→이, subiect), 일 (consoană→을, obiect)","en":"몸 (consonant→이, subject), 일 (consonant→을, object)"}},
    {"lessonId":"T4-07","topik":4,"template":"규칙___ 지키는 한 여기___ 있어도 돼요.","options":[["을","에"],["이","에"],["를","에"],["을","는"]],"correct":["을","에"],"hint":{"ro":"규칙 (consoană→을, obiect), 여기에 = aici (particulă locație 에)","en":"규칙 (consonant→을, object), 여기에 = here (location particle 에)"}},
    {"lessonId":"T4-08","topik":4,"template":"도시___ 편리한 반면 시골___ 조용해요.","options":[["는","은"],["가","은"],["는","이"],["이","은"]],"correct":["는","은"],"hint":{"ro":"도시 (vocală→는, topic), 시골 (consoană→은, topic)","en":"도시 (vowel→는, topic), 시골 (consonant→은, topic)"}},
    {"lessonId":"T4-08","topik":4,"template":"여름___ 더운 반면 겨울___ 추워요.","options":[["은","은"],["이","은"],["은","이"],["는","은"]],"correct":["은","은"],"hint":{"ro":"여름 (consoană→은, topic), 겨울 (consoană→은, topic)","en":"여름 (consonant→은, topic), 겨울 (consonant→은, topic)"}},
    {"lessonId":"T4-09","topik":4,"template":"케이크___ 다 먹고 과자___ 먹어 버렸어요.","options":[["를","도"],["을","도"],["가","도"],["를","이"]],"correct":["를","도"],"hint":{"ro":"케이크 (vocală→를, obiect), 과자도 = și biscuiții (도)","en":"케이크 (vowel→를, object), 과자도 = also snacks (도)"}},
    {"lessonId":"T4-09","topik":4,"template":"지갑___ 잃어 버려서 돈___ 없어요.","options":[["을","이"],["를","이"],["을","가"],["이","가"]],"correct":["을","이"],"hint":{"ro":"지갑 (consoană→을, obiect), 돈 (consoană→이, subiect)","en":"지갑 (consonant→을, object), 돈 (consonant→이, subject)"}},
    {"lessonId":"T4-10","topik":4,"template":"밥___ 먹다가 전화___ 왔어요.","options":[["을","가"],["이","가"],["를","가"],["을","이"]],"correct":["을","가"],"hint":{"ro":"밥 (consoană→을, obiect), 전화 (vocală→가, subiect)","en":"밥 (consonant→을, object), 전화 (vowel→가, subject)"}},
    {"lessonId":"T4-10","topik":4,"template":"음악___ 듣다가 갑자기 잠___ 들었어요.","options":[["을","이"],["이","이"],["를","이"],["을","가"]],"correct":["을","이"],"hint":{"ro":"음악 (consoană→을, obiect), 잠이 들다 = a adormi (expresie fixă)","en":"음악 (consonant→을, object), 잠이 들다 = to fall asleep (fixed expression)"}},
    {"lessonId":"T4-11","topik":4,"template":"시험___ 없었으면 좋겠고 숙제___ 없었으면 좋겠어요.","options":[["이","도"],["가","도"],["이","는"],["를","도"]],"correct":["이","도"],"hint":{"ro":"시험 (consoană→이, subiect), 숙제도 = și temele (도)","en":"시험 (consonant→이, subject), 숙제도 = also homework (도)"}},
    {"lessonId":"T4-11","topik":4,"template":"방학___ 더 길고 수업___ 더 재미있었으면 좋겠어요.","options":[["이","도"],["가","도"],["이","이"],["를","도"]],"correct":["이","도"],"hint":{"ro":"방학 (consoană→이, subiect), 수업도 = și orele (도)","en":"방학 (consonant→이, subject), 수업도 = also classes (도)"}},
]

new_conjug = [
    {"lessonId":"T4-01","topik":4,"prompt":{"ro":"오다 → va veni (presupunere viitor cu -(으)ㄹ 것 같다)","en":"오다 → will come (future conjecture -(으)ㄹ 것 같다)"},"options":["올 것 같아요","오을 것 같아요","오는 것 같아요","온 것 같아요"],"correct":"올 것 같아요"},
    {"lessonId":"T4-01","topik":4,"prompt":{"ro":"화나다 → se pare că s-a supărat (presupunere trecut -(으)ㄴ 것 같다)","en":"화나다 → seems to have gotten angry (past conjecture -(으)ㄴ 것 같다)"},"options":["화난 것 같아요","화나은 것 같아요","화나는 것 같아요","화났은 것 같아요"],"correct":"화난 것 같아요"},
    {"lessonId":"T4-02","topik":4,"prompt":{"ro":"건강해지다 → ca să devii sănătos (-도록)","en":"건강해지다 → so that you become healthy (-도록)"},"options":["건강해지도록","건강해지었도록","건강해지는도록","건강해진도록"],"correct":"건강해지도록"},
    {"lessonId":"T4-02","topik":4,"prompt":{"ro":"합격하다 → ca să promovezi (-도록)","en":"합격하다 → so that you pass (-도록)"},"options":["합격하도록","합격했도록","합격하는도록","합격한도록"],"correct":"합격하도록"},
    {"lessonId":"T4-03","topik":4,"prompt":{"ro":"알다 → cu cât știi mai mult (-(으)ㄹ수록, tulpină ㄹ)","en":"알다 → the more you know (-(으)ㄹ수록, ㄹ stem)"},"options":["알수록","아는수록","알은수록","알을수록"],"correct":"알수록"},
    {"lessonId":"T4-03","topik":4,"prompt":{"ro":"연습하다 → cu cât exersezi mai mult (-(으)ㄹ수록)","en":"연습하다 → the more you practice (-(으)ㄹ수록)"},"options":["연습할수록","연습하는수록","연습한수록","연습했을수록"],"correct":"연습할수록"},
    {"lessonId":"T4-04","topik":4,"prompt":{"ro":"다르다 → diferă (prezent politicos, neregulat 르)","en":"다르다 → differs (polite present, 르 irregular)"},"options":["달라요","다르아요","다릅니다","다르어요"],"correct":"달라요"},
    {"lessonId":"T4-04","topik":4,"prompt":{"ro":"따르다 → conform (prezent formal -ㅂ니다, neregulat 르)","en":"따르다 → according to (formal present -ㅂ니다, 르 irregular)"},"options":["따릅니다","따르습니다","따랍니다","따르입니다"],"correct":"따릅니다"},
    {"lessonId":"T4-05","topik":4,"prompt":{"ro":"먹다 → deși a mâncat (verb + -(으)ㄴ 데도, aspect completat)","en":"먹다 → even though ate (verb + -(으)ㄴ 데도, completed)"},"options":["먹은 데도","먹는 데도","먹을 데도","먹었는 데도"],"correct":"먹은 데도"},
    {"lessonId":"T4-05","topik":4,"prompt":{"ro":"피곤하다 → deși este obosit (adjectiv + -(으)ㄴ 데도)","en":"피곤하다 → even though tired (adjective + -(으)ㄴ 데도)"},"options":["피곤한 데도","피곤하는 데도","피곤했는 데도","피곤할 데도"],"correct":"피곤한 데도"},
    {"lessonId":"T4-06","topik":4,"prompt":{"ro":"살다 → trăind (formă cu -다 보니)","en":"살다 → having lived (-다 보니 form)"},"options":["살다 보니","사는 보니","살았다 보니","사니"],"correct":"살다 보니"},
    {"lessonId":"T4-06","topik":4,"prompt":{"ro":"여행하다 → călătorind mereu (-다 보니)","en":"여행하다 → having kept traveling (-다 보니)"},"options":["여행하다 보니","여행했다 보니","여행하는 보니","여행한 보니"],"correct":"여행하다 보니"},
    {"lessonId":"T4-07","topik":4,"prompt":{"ro":"건강하다 → cât timp ești sănătos (adjectiv + -(으)ㄴ 한)","en":"건강하다 → as long as healthy (adjective + -(으)ㄴ 한)"},"options":["건강한 한","건강하는 한","건강할 한","건강했는 한"],"correct":"건강한 한"},
    {"lessonId":"T4-07","topik":4,"prompt":{"ro":"지키다 → cât timp respecți (verb + -는 한)","en":"지키다 → as long as you follow (verb + -는 한)"},"options":["지키는 한","지킨 한","지킬 한","지켰는 한"],"correct":"지키는 한"},
    {"lessonId":"T4-08","topik":4,"prompt":{"ro":"편리하다 → este convenabil, în schimb (adjectiv + -(으)ㄴ 반면에)","en":"편리하다 → is convenient, whereas (adjective + -(으)ㄴ 반면에)"},"options":["편리한 반면에","편리하는 반면에","편리할 반면에","편리했는 반면에"],"correct":"편리한 반면에"},
    {"lessonId":"T4-08","topik":4,"prompt":{"ro":"덥다 → este cald, pe de altă parte (adj ㅂ-neregulat + -(으)ㄴ 반면에)","en":"덥다 → is hot, whereas (ㅂ-irregular adj + -(으)ㄴ 반면에)"},"options":["더운 반면에","덥은 반면에","더버는 반면에","덥는 반면에"],"correct":"더운 반면에"},
    {"lessonId":"T4-09","topik":4,"prompt":{"ro":"먹다 → a mâncat tot (-아/어 버리다, trecut)","en":"먹다 → ate it all up (-아/어 버리다, past)"},"options":["먹어 버렸어요","먹아 버렸어요","먹었어 버렸어요","먹으어 버렸어요"],"correct":"먹어 버렸어요"},
    {"lessonId":"T4-09","topik":4,"prompt":{"ro":"잃다 → a pierdut (-아/어 버리다, trecut)","en":"잃다 → lost it (-아/어 버리다, past)"},"options":["잃어 버렸어요","잃아 버렸어요","잃으어 버렸어요","잃었어 버렸어요"],"correct":"잃어 버렸어요"},
    {"lessonId":"T4-10","topik":4,"prompt":{"ro":"먹다 → în timp ce mânca (-다가)","en":"먹다 → while eating (-다가)"},"options":["먹다가","먹어다가","먹었다가","먹는다가"],"correct":"먹다가"},
    {"lessonId":"T4-10","topik":4,"prompt":{"ro":"듣다 → în timp ce asculta (ㄷ-neregulat + -다가)","en":"듣다 → while listening (ㄷ-irregular + -다가)"},"options":["듣다가","들다가","드러다가","듣어다가"],"correct":"듣다가"},
    {"lessonId":"T4-11","topik":4,"prompt":{"ro":"없다 → mi-ar plăcea să nu existe (-었으면 좋겠다)","en":"없다 → I wish it didn't exist (-었으면 좋겠다)"},"options":["없었으면 좋겠어요","없으면 좋겠어요","없어었으면 좋겠어요","없었면 좋겠어요"],"correct":"없었으면 좋겠어요"},
    {"lessonId":"T4-11","topik":4,"prompt":{"ro":"길다 → mi-ar plăcea să fie mai lung (-었으면 좋겠다)","en":"길다 → I wish it were longer (-었으면 좋겠다)"},"options":["길었으면 좋겠어요","기었으면 좋겠어요","길으면 좋겠어요","길었면 좋겠어요"],"correct":"길었으면 좋겠어요"},
]

new_puzzle = [
    {"lessonId":"T4-01","topik":4,"tiles":["비가","오늘","올","것","같아요"],"correct":["오늘","비가","올","것","같아요"],"hint":{"ro":"Pare că azi va ploua.","en":"It seems like it will rain today."}},
    {"lessonId":"T4-01","topik":4,"tiles":["화가","그","난","사람이","것","같아요"],"correct":["그","사람이","화가","난","것","같아요"],"hint":{"ro":"Se pare că acea persoană e supărată.","en":"It seems like that person is angry."}},
    {"lessonId":"T4-02","topik":4,"tiles":["운동해요","건강해지도록","매일"],"correct":["건강해지도록","매일","운동해요"],"hint":{"ro":"Fac sport în fiecare zi ca să mă fac sănătos.","en":"I exercise every day so that I become healthy."}},
    {"lessonId":"T4-02","topik":4,"tiles":["공부해요","열심히","시험에","합격하도록"],"correct":["시험에","합격하도록","열심히","공부해요"],"hint":{"ro":"Studiez din greu ca să promovez examenul.","en":"I study hard so that I pass the exam."}},
    {"lessonId":"T4-03","topik":4,"tiles":["어려워요","알수록","더"],"correct":["알수록","더","어려워요"],"hint":{"ro":"Cu cât știi mai multe, cu atât devine mai greu.","en":"The more you know, the harder it gets."}},
    {"lessonId":"T4-03","topik":4,"tiles":["실력이","연습할수록","늘어요","한국어는"],"correct":["한국어는","연습할수록","실력이","늘어요"],"hint":{"ro":"Cu cât exersezi mai mult coreana, cu atât nivelul crește.","en":"The more you practice Korean, the better you get."}},
    {"lessonId":"T4-04","topik":4,"tiles":["달라요","사람에","의견이","따라"],"correct":["사람에","따라","의견이","달라요"],"hint":{"ro":"Opiniile diferă în funcție de persoană.","en":"Opinions differ depending on the person."}},
    {"lessonId":"T4-04","topik":4,"tiles":["수면이","연구에","중요하다고","따르면","해요"],"correct":["연구에","따르면","수면이","중요하다고","해요"],"hint":{"ro":"Conform cercetărilor, se spune că somnul este important.","en":"According to research, sleep is said to be important."}},
    {"lessonId":"T4-05","topik":4,"tiles":["배가","데도","먹은","고파요"],"correct":["먹은","데도","배가","고파요"],"hint":{"ro":"Deși am mâncat, îmi este foame.","en":"Even though I ate, I'm still hungry."}},
    {"lessonId":"T4-05","topik":4,"tiles":["계속했어요","피곤한","일을","데도"],"correct":["피곤한","데도","일을","계속했어요"],"hint":{"ro":"Deși eram obosit, am continuat să lucrez.","en":"Even though I was tired, I continued working."}},
    {"lessonId":"T4-06","topik":4,"tiles":["배우게","혼자","요리를","살다","됐어요","보니"],"correct":["혼자","살다","보니","요리를","배우게","됐어요"],"hint":{"ro":"Trăind singur, am ajuns să învăț să gătesc.","en":"As I kept living alone, I ended up learning to cook."}},
    {"lessonId":"T4-06","topik":4,"tiles":["알게","많이","여행을","보니","새로운","됐어요","하다","문화를"],"correct":["여행을","많이","하다","보니","새로운","문화를","알게","됐어요"],"hint":{"ro":"Călătorind mult, am ajuns să cunosc culturi noi.","en":"As I kept traveling a lot, I got to know new cultures."}},
    {"lessonId":"T4-07","topik":4,"tiles":["일을","한","건강한","거예요","계속할"],"correct":["건강한","한","일을","계속할","거예요"],"hint":{"ro":"Cât timp sunt sănătos, voi continua să lucrez.","en":"As long as I'm healthy, I'll continue working."}},
    {"lessonId":"T4-07","topik":4,"tiles":["문제없어요","한","규칙을","지키는"],"correct":["규칙을","지키는","한","문제없어요"],"hint":{"ro":"Cât timp respecți regulile, nu e nicio problemă.","en":"As long as you follow the rules, there's no problem."}},
    {"lessonId":"T4-08","topik":4,"tiles":["반면","시끄러워요","도시는","편리한"],"correct":["도시는","편리한","반면","시끄러워요"],"hint":{"ro":"Orașul este convenabil, dar în schimb e zgomotos.","en":"The city is convenient, but on the other hand it's noisy."}},
    {"lessonId":"T4-08","topik":4,"tiles":["겨울은","더운","여름은","반면","추워요"],"correct":["여름은","더운","반면","겨울은","추워요"],"hint":{"ro":"Vara este caldă, în schimb iarna este friguroasă.","en":"Summer is hot, whereas winter is cold."}},
    {"lessonId":"T4-09","topik":4,"tiles":["버렸어요","다","케이크를","먹어"],"correct":["케이크를","다","먹어","버렸어요"],"hint":{"ro":"Am mâncat tot tortul.","en":"I ate all the cake."}},
    {"lessonId":"T4-09","topik":4,"tiles":["버렸어요","지갑을","잃어"],"correct":["지갑을","잃어","버렸어요"],"hint":{"ro":"Mi-am pierdut portofelul.","en":"I lost my wallet."}},
    {"lessonId":"T4-10","topik":4,"tiles":["전화가","밥을","왔어요","먹다가"],"correct":["밥을","먹다가","전화가","왔어요"],"hint":{"ro":"În timp ce mâncam, a venit un apel telefonic.","en":"While eating, a phone call came."}},
    {"lessonId":"T4-10","topik":4,"tiles":["잠이","음악을","들었어요","듣다가"],"correct":["음악을","듣다가","잠이","들었어요"],"hint":{"ro":"În timp ce ascultam muzică, am adormit.","en":"While listening to music, I fell asleep."}},
    {"lessonId":"T4-11","topik":4,"tiles":["좋겠어요","없었으면","시험이"],"correct":["시험이","없었으면","좋겠어요"],"hint":{"ro":"Mi-ar plăcea să nu fie examene.","en":"I wish there were no exams."}},
    {"lessonId":"T4-11","topik":4,"tiles":["좋겠어요","더","방학이","길었으면"],"correct":["방학이","더","길었으면","좋겠어요"],"hint":{"ro":"Mi-ar plăcea ca vacanța să fie mai lungă.","en":"I wish the vacation were longer."}},
]

new_chain = [
    {"lessonId":"T4-01","topik":4,"tiles":["비가 올 것 같아요.","오늘 날씨가 흐려요.","조심히 나가세요.","우산을 가져가는 게 좋을 것 같아요."],"correct":["오늘 날씨가 흐려요.","비가 올 것 같아요.","우산을 가져가는 게 좋을 것 같아요.","조심히 나가세요."],"context":{"ro":"Previziune meteo și sfat","en":"Weather forecast and advice"}},
    {"lessonId":"T4-01","topik":4,"tiles":["그 사람이 화가 난 것 같아요.","무슨 일이 있었어요?","제가 실수를 했어요.","잘못을 인정하고 사과해야 할 것 같아요."],"correct":["무슨 일이 있었어요?","그 사람이 화가 난 것 같아요.","제가 실수를 했어요.","잘못을 인정하고 사과해야 할 것 같아요."],"context":{"ro":"Situație tensionată și soluție","en":"Tense situation and solution"}},
    {"lessonId":"T4-02","topik":4,"tiles":["건강이 중요해요.","건강해지도록 매일 운동해요.","균형 잡힌 식사도 해요.","덕분에 몸이 좋아졌어요."],"correct":["건강이 중요해요.","건강해지도록 매일 운동해요.","균형 잡힌 식사도 해요.","덕분에 몸이 좋아졌어요."],"context":{"ro":"Rutina de sănătate","en":"Health routine"}},
    {"lessonId":"T4-02","topik":4,"tiles":["내일 중요한 시험이 있어요.","시험에 합격하도록 열심히 공부해요.","밤늦게까지 공부했어요.","합격할 수 있을 것 같아요."],"correct":["내일 중요한 시험이 있어요.","시험에 합격하도록 열심히 공부해요.","밤늦게까지 공부했어요.","합격할 수 있을 것 같아요."],"context":{"ro":"Pregătire pentru examen","en":"Preparing for an exam"}},
    {"lessonId":"T4-03","topik":4,"tiles":["한국어 공부를 시작했어요.","알수록 더 어려워요.","하지만 포기하지 않을 거예요.","꾸준히 연습하면 나아질 거예요."],"correct":["한국어 공부를 시작했어요.","알수록 더 어려워요.","하지만 포기하지 않을 거예요.","꾸준히 연습하면 나아질 거예요."],"context":{"ro":"Învățarea limbii coreene","en":"Learning Korean"}},
    {"lessonId":"T4-03","topik":4,"tiles":["처음에는 한국어가 너무 어려웠어요.","연습할수록 실력이 늘어요.","지금은 많이 좋아졌어요.","앞으로도 열심히 공부할 거예요."],"correct":["처음에는 한국어가 너무 어려웠어요.","연습할수록 실력이 늘어요.","지금은 많이 좋아졌어요.","앞으로도 열심히 공부할 거예요."],"context":{"ro":"Progres în coreeană","en":"Progress in Korean"}},
    {"lessonId":"T4-04","topik":4,"tiles":["왜 의견이 다양할까요?","사람에 따라 의견이 달라요.","각자 경험이 다르기 때문이에요.","서로의 의견을 존중해야 해요."],"correct":["왜 의견이 다양할까요?","사람에 따라 의견이 달라요.","각자 경험이 다르기 때문이에요.","서로의 의견을 존중해야 해요."],"context":{"ro":"Diversitatea opiniilor","en":"Diversity of opinions"}},
    {"lessonId":"T4-04","topik":4,"tiles":["충분한 수면이 중요해요.","연구에 따르면 수면이 중요하다고 해요.","매일 7시간 이상 자야 해요.","잠이 부족하면 건강에 나빠요."],"correct":["충분한 수면이 중요해요.","연구에 따르면 수면이 중요하다고 해요.","매일 7시간 이상 자야 해요.","잠이 부족하면 건강에 나빠요."],"context":{"ro":"Importanța somnului","en":"The importance of sleep"}},
    {"lessonId":"T4-05","topik":4,"tiles":["아직도 배가 고파요.","방금 점심을 먹었는데요.","먹은 데도 배가 고파요.","조금 더 먹을까요?"],"correct":["방금 점심을 먹었는데요.","아직도 배가 고파요.","먹은 데도 배가 고파요.","조금 더 먹을까요?"],"context":{"ro":"Foame după masă","en":"Still hungry after eating"}},
    {"lessonId":"T4-05","topik":4,"tiles":["오늘 정말 피곤해요.","하지만 할 일이 너무 많아요.","피곤한 데도 일을 계속했어요.","끝내고 나서 쉬어야겠어요."],"correct":["오늘 정말 피곤해요.","하지만 할 일이 너무 많아요.","피곤한 데도 일을 계속했어요.","끝내고 나서 쉬어야겠어요."],"context":{"ro":"Muncind în ciuda oboselii","en":"Working despite exhaustion"}},
    {"lessonId":"T4-06","topik":4,"tiles":["혼자 살기 시작했어요.","처음에는 요리를 못 했어요.","혼자 살다 보니 요리를 배우게 됐어요.","이제는 맛있는 음식을 만들 수 있어요."],"correct":["혼자 살기 시작했어요.","처음에는 요리를 못 했어요.","혼자 살다 보니 요리를 배우게 됐어요.","이제는 맛있는 음식을 만들 수 있어요."],"context":{"ro":"Viața de unul singur","en":"Living alone"}},
    {"lessonId":"T4-06","topik":4,"tiles":["여행을 많이 했어요.","다양한 나라를 방문했어요.","여행을 많이 하다 보니 새로운 문화를 알게 됐어요.","세계가 넓고 다양하다고 느꼈어요."],"correct":["여행을 많이 했어요.","다양한 나라를 방문했어요.","여행을 많이 하다 보니 새로운 문화를 알게 됐어요.","세계가 넓고 다양하다고 느꼈어요."],"context":{"ro":"Descoperirea lumii prin călătorii","en":"Discovering the world through travel"}},
    {"lessonId":"T4-07","topik":4,"tiles":["건강이 제일 중요해요.","건강한 한 일을 계속할 거예요.","하지만 과로는 피해야 해요.","균형 있는 생활이 중요해요."],"correct":["건강이 제일 중요해요.","건강한 한 일을 계속할 거예요.","하지만 과로는 피해야 해요.","균형 있는 생활이 중요해요."],"context":{"ro":"Echilibrul dintre sănătate și muncă","en":"Balance between health and work"}},
    {"lessonId":"T4-07","topik":4,"tiles":["여기서는 규칙을 지켜야 해요.","규칙을 지키는 한 문제없어요.","모두가 규칙을 따르면 안전해요.","서로를 위해 규칙을 존중해요."],"correct":["여기서는 규칙을 지켜야 해요.","규칙을 지키는 한 문제없어요.","모두가 규칙을 따르면 안전해요.","서로를 위해 규칙을 존중해요."],"context":{"ro":"Importanța regulilor","en":"The importance of rules"}},
    {"lessonId":"T4-08","topik":4,"tiles":["도시와 시골은 달라요.","도시는 편리한 반면 시끄러워요.","시골은 불편하지만 조용해요.","각자 좋아하는 곳이 달라요."],"correct":["도시와 시골은 달라요.","도시는 편리한 반면 시끄러워요.","시골은 불편하지만 조용해요.","각자 좋아하는 곳이 달라요."],"context":{"ro":"Orașul versus satul","en":"City versus countryside"}},
    {"lessonId":"T4-08","topik":4,"tiles":["한국의 사계절이 뚜렷해요.","여름은 더운 반면 겨울은 추워요.","봄과 가을은 따뜻하고 시원해요.","각 계절마다 다른 매력이 있어요."],"correct":["한국의 사계절이 뚜렷해요.","여름은 더운 반면 겨울은 추워요.","봄과 가을은 따뜻하고 시원해요.","각 계절마다 다른 매력이 있어요."],"context":{"ro":"Anotimpurile Coreei","en":"The seasons of Korea"}},
    {"lessonId":"T4-09","topik":4,"tiles":["생일 파티를 했어요.","케이크가 정말 맛있었어요.","케이크를 다 먹어 버렸어요.","나중에 배가 아팠어요."],"correct":["생일 파티를 했어요.","케이크가 정말 맛있었어요.","케이크를 다 먹어 버렸어요.","나중에 배가 아팠어요."],"context":{"ro":"Petrecere de ziua de naștere","en":"Birthday party"}},
    {"lessonId":"T4-09","topik":4,"tiles":["오늘 정말 힘든 날이었어요.","지갑을 잃어 버렸어요.","경찰서에 신고했어요.","다행히 지갑을 찾았어요."],"correct":["오늘 정말 힘든 날이었어요.","지갑을 잃어 버렸어요.","경찰서에 신고했어요.","다행히 지갑을 찾았어요."],"context":{"ro":"O zi dificilă","en":"A difficult day"}},
    {"lessonId":"T4-10","topik":4,"tiles":["밥을 먹고 있었어요.","밥을 먹다가 전화가 왔어요.","중요한 전화였어요.","밥을 다 못 먹었어요."],"correct":["밥을 먹고 있었어요.","밥을 먹다가 전화가 왔어요.","중요한 전화였어요.","밥을 다 못 먹었어요."],"context":{"ro":"Întrerupt de un telefon","en":"Interrupted by a phone call"}},
    {"lessonId":"T4-10","topik":4,"tiles":["음악을 들으면서 공부했어요.","음악을 듣다가 잠이 들었어요.","한 시간 동안 잤어요.","일어나서 다시 공부를 시작했어요."],"correct":["음악을 들으면서 공부했어요.","음악을 듣다가 잠이 들었어요.","한 시간 동안 잤어요.","일어나서 다시 공부를 시작했어요."],"context":{"ro":"Adormit în timp ce studiam","en":"Fell asleep while studying"}},
    {"lessonId":"T4-11","topik":4,"tiles":["내일 시험이 있어요.","시험이 없었으면 좋겠어요.","하지만 열심히 준비했어요.","잘 볼 수 있을 것 같아요."],"correct":["내일 시험이 있어요.","시험이 없었으면 좋겠어요.","하지만 열심히 준비했어요.","잘 볼 수 있을 것 같아요."],"context":{"ro":"Înainte de examen","en":"Before the exam"}},
    {"lessonId":"T4-11","topik":4,"tiles":["방학이 곧 끝나요.","방학이 더 길었으면 좋겠어요.","하지만 학교도 그리워요.","새 학기를 잘 시작해야겠어요."],"correct":["방학이 곧 끝나요.","방학이 더 길었으면 좋겠어요.","하지만 학교도 그리워요.","새 학기를 잘 시작해야겠어요."],"context":{"ro":"Sfârșitul vacanței","en":"The end of the vacation"}},
]

data['ko-ro'].extend(new_ko_ro)
data['ro-ko'].extend(new_ro_ko)
data['particle'].extend(new_particle)
data['particlePlus'].extend(new_particle_plus)
data['conjug'].extend(new_conjug)
data['puzzle'].extend(new_puzzle)
data['chain'].extend(new_chain)

with open('data/exercises.json', 'w', encoding='utf-8') as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

print("Done! New counts:")
print({k: len(v) for k, v in data.items()})
